### ISSUE TITLE
problem in compile of glpk related code

### ISSUE THREAD

**Issue by raphyz** [ModelSEED/Model-SEED-core#10]
in all make files of mfatoolkt/linux
there is a line:
GLPKLIB = $(GLPKDIRECTORY)/src/.libs/

which points to the glpk lib path.

It looks like an error and should maybe /src/../lib/

**Comment by raphyz** [comment]
I had also problems with the name of the ilog cplex library which was writen as -cplex when it was realy for my version of cplex libcplex110.so (which is cplex110.

If I am not a special case, then maybe specific parameters are due, or a search should be executed for the right value and not a hardcoded value...

**Comment by cshenry** [comment]
So I broke out the GLPK parameters into a separate parameter for the library directory and the include directory. I'm hoping this fixes that issue.

As for cplex, that remains an open issue... probably needs to be yet another parameter.

**Comment by samseaver** [comment]
Compilation for glpk and cplex now works for me on both my mac laptop and in the BIO environment.  I had to be specific about the cplex and include library path in the config file:

includeDirectoryCPLEX=/Users/seaver/Software/CPlex/cplex/include/ilcplex
libraryDirectoryCPLEX=/Users/seaver/Software/CPlex/cplex/lib/x86_darwin9_gcc4.0/static_pic
