### ISSUE TITLE
Java classpath on biologin-4

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#104]
I couldn't use MarvinBeans within a perl script, whether I used it from ~chenry or ~seaver on biologin-4, I kept getting the same "class not found" errors.

It also requires an academic license to use, so I'm waiting for this to be approved so I can use it on my mac.  The point being is that both CPLEX and MarvinBeans require licenses so we should have that in the documentation somewhere.

**Comment by devoid** [comment]
Closing. Not directly related to codebase.
