### ISSUE TITLE
GLPK on biologin-4

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#108]
This may not be an important issue, but I just did a git pull and ran

/vol/model-prod/env/config.sh

on biologin-4 for the first time in a while, and even though it ran fine, I did get a warning about a missing executable:

'which: no glpsol'

I don't know if this is even relevant, but I'm posting it here in case.

**Comment by devoid** [comment]
Relevant for using glpk, but the biologin-4 env has CPLEX so that's sufficient.
