### ISSUE TITLE
One-step installation script

### ISSUE THREAD

**Issue by devoid** [ModelSEED/Model-SEED-core#11]
I've written an installation script [`bootstrap.sh`](https://github.com/devoid/Model-SEED-core/blob/7515d274cdda154a88b093c06c0b3e410bd906da/lib/ModelSEED/ModelSEEDScripts/bootstrap.sh).

Called with this syntax:
`bootstrap.sh path/to/install`

It does the following:
1. Checkout latest version of Model-SEED-core repository
2. Download and install flatfile data from http://bioseed.mcs.anl.gov/~chenry/data.tgz ( in `data/` )
3. Downlaod and install ModelDB database (sqlite) from http://bioseed.mcs.anl.gov/~devoid/ModelDB-sqlite.tgz

At that point, you need to edit your configuration, specifically to point ms-config at the GLPK lib dir.

Then you run `bin/ms-config load` to complete everything.

Ideally we could automatically discover the location of the GLPK directory, then you'd have a working ModelSEED install after running one command. No reading instructions, no additional downloads.

**Comment by samseaver** [comment]
I tested this script, it worked fine on my mac laptop but for two things:

1) The script itself is only available in the devoid fork right now
2) It's still pointing to the cshenry repo when attempting to clone

**Comment by samseaver** [comment]
the config/Settings.config file points to a sqlite database filename that has the *.sqlite suffix.

However, the bootstrap.sh file deletes this file after it creates the database file, with the *.db suffix

**Comment by samseaver** [comment]
bin/ms-config ran fine, with the exception that I had to install the Config::Tiny perl module.  But after that, it compiled everything just right.

However, when I ran bin/ModelDriver thus:

bin/ModelDriver importmodel?KEGGimport?83333.1?seaver?/Users/seaver/Documents/Projects/Model_Import_Files/?1

I got this error:

Failure running /Users/seaver/Software/Model-SEED-core-test/lib/ModelSEED/ModelDriver.pl: Can't call method "USERS" on an undefined value at /Users/seaver/Software/Model-SEED-core-test/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 171.

**Comment by devoid** [comment]
Users should be working now.
