### ISSUE TITLE
Genome ids when printing/loading models

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#110]
If I were to send someone a model I print from my database, I would have to tell them the genome id to use when to load the model into their database.  It would instead be helpful if genome ids were somehow included in the printed model file.

I understand however that since the same function is used to print individual model files for FBA purposes, this may not be a trivial matter, it may be that we should have a separate function for printing model files that contains more information about the model for use with the mdl-loadmodel function.

This goes back to our discussion earlier this week about objects with parameters built-in to reduce the typing needed to run functions again in the same manner, the same would apply to the model objects we print and share.

**Comment by devoid** [comment]
Closed as won't fix. New schema solves this.
