### ISSUE TITLE
Number of characters limit for 'alias' in COMPOUND_ALIAS table

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#112]
Guess what, my newly formed InChI strings are now too long.  I'm not sure why I didn't get this problem with the SQLite table, presumably because it doesn't do this like MySQL does, but here's what happens:

I have two InChI strings for one compound that are 359 characters in length.  The only difference in the characters are at the end of the string, and so, when the first one is inserted into the COMPOUND_ALIAS table, it is truncated to 255 characters, and then when the code attempts to insert the second one, it rejects it because the truncated 255 string has an identical string already in the table.

The longest InChI strings I've got right now are 1387 characters in length, can I get a upper limit of like 5000 characters for the alias column please.

I'd attempt to change this myself, but I'm not too familiar with the current DB schema.

**Comment by samseaver** [comment]
I just figured out that I can work around this by using the provenance of the TestModel that I imported, but the issue remains, InChI strings are loooong.

**Comment by devoid** [comment]
We will have to figure out what to do with compound structures. The new schema has no immediate limits on alias string sizes.
