### ISSUE TITLE
User account on biologin-4

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#118]
I'm logged in, and actively using my workspace with my account on biologin-4, but I just realized that I do not have a row in the USERS table in ModelDB.  We'd been talking about my (in)ability to access my models in ModelSEED, and it seems that this may be why.

I don't remember what I did to 'create' my account, but if the code has been updated since (its been a while, it may be that my account creation on biologin-4 borrowed from the SEED accounts), I'll try re-creating the account and see if I get an entry.

As of now, however, there are only two entries, Matt and Jose, so if others have been creating accounts, I don't know why they don't have rows in the USERS table.

**Comment by devoid** [comment]
If you have correctly done the configuration for running ModelSEED in the bio-\* environment, it should use the `User` table in `WebAppBackend` not the ModelDB table. However, if the configuration was not done properly, it will try to use the "USERS" table in ModelDB.
