### ISSUE TITLE
Autocomplete Failing

### ISSUE THREAD

**Issue by jamesclulow** [ModelSEED/Model-SEED-core#126]
I created a new model today, ran the reconstruction algorithm, and then tried to autocomplete only to get the following error:

tsf-wpa-1-2129:bin jamesclulow$ ./mdl-autocomplete -model Seed392499.4.46352
Creating problem directory: 24
Creating list of inactive reactions: /Users/jamesclulow/Desktop/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/24/InactiveModelReactions.txt
Printing gapfilling parameters in : /Users/jamesclulow/Desktop/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/24/CompleteGapfillingParameters.txt
Running runFBAStudy
Using problem directory: 24
Creating the model file: /Users/jamesclulow/Desktop/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/24/Seed392499.4.46352.tbl
Creating biochemistry provenance files
Running FBA
mkdir: /Users/jamesclulow/Desktop/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/24/MFAOutput: File exists
sh: line 1:  4778 Segmentation fault: 11  /Users/jamesclulow/Desktop/Model-SEED-core/software/mfatoolkit/bin/mfatoolkit resetparameter "MFA input directory" /Users/jamesclulow/Desktop/Model-SEED-core/data/ReactionDB/ parameterfile "../Parameters/ProductionMFA.txt" parameterfile "../Parameters/GapFilling.txt" parameterfile "/Users/jamesclulow/Desktop/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/24/CompleteGapfillingParameters.txt" parameterfile "/Users/jamesclulow/Desktop/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/24/AddnlFBAParameters.txt" LoadCentralSystem "/Users/jamesclulow/Desktop/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/24/Seed392499.4.46352.tbl" > "/Users/jamesclulow/Desktop/Model-SEED-core/logs/fba-24.log"
Parsing results
Finished runFBAStudy
Whoops! We encountered an unrecoverable error.

Gapfilling of model Seed392499.4.46352 failed!

A complete log of the problem has been printed to:

/Users/jamesclulow/Desktop/Model-SEED-core/.errors/error-rwHz3

Have you updated recently? ( git pull )
Have you changed your configuration? ( ms-config )

If you are still having problems, please submit a ticket
copying the contents of the error file printed above to:

https://github.com/ModelSEED/Model-SEED-core/issues/new

Thanks!

The error file reads as:

> ModelDriver encountered an unrecoverable error:

```
""Gapfilling of model Seed392499.4.46352 failed!"" at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/globals.pm line 91
    ModelSEED::globals::ERROR('Gapfilling of model Seed392499.4.46352 failed!') called at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELmodel.pm line 2120
    ModelSEED::FIGMODEL::FIGMODELmodel::completeGapfilling('ModelSEED::FIGMODEL::FIGMODELmodel=HASH(0x7f9aecf1a678)', 'HASH(0x7f9aeced8278)') called at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pm line 6685
    ModelSEED::ModelDriver::mdlautocomplete('ModelSEED::ModelDriver=HASH(0x7f9aee18aee0)', 'mdlautocomplete', 'HASH(0x7f9aea82e3e0)') called at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 90
    main::__ANON__() called at /Library/Perl/5.12/Try/Tiny.pm line 76
    eval {...} called at /Library/Perl/5.12/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x7f9aea832f68)', 'Try::Tiny::Catch=REF(0x7f9aea833c28)') called at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 94
    require /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pl called at /Users/jamesclulow/Desktop/Model-SEED-core/config//ModelSEEDbootstrap.pm line 24
    main::run() called at -e line 3
```

I am not sure if it is a problem with my MFAToolkit? Any suggestions?

**Comment by samseaver** [comment]
A seg fault is hard to debug unfortunately, but are you able to use fba-checkgrowth?  Even if it cannot grow, knowing whether this simpler FBA problem runs or not helps.

**Comment by jamesclulow** [comment]
It doesn't grow due to various Biomass compounds which cannot be generated. This is what I see when I get run FBA-checkgrowth

wl1-228-132:bin jamesclulow$ ./fba-checkgrowth -model Seed392499.4.46352Using problem directory: 26
Creating the model file: /Users/jamesclulow/Desktop/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/26/Seed392499.4.46352.tbl
Creating biochemistry provenance files
Running FBA
mkdir: /Users/jamesclulow/Desktop/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/26/MFAOutput: File exists
Parsing results
Seed392499.4.46352 failed to grow in Complete media.
Biomass compounds cpd15665,cpd00220,cpd15432,cpd00016,cpd00062,cpd00010,cpd00006,cpd00063,cpd00015,cpd00038,cpd00003,cpd02229,cpd00356,cpd11493,cpd00241,cpd00065,cpd00052,cpd00030 could not be generated!

**Comment by samseaver** [comment]
Chris has gotten autocomplete to work, please do a git pull and try again.

I'm closing this issue, but you can re-open if you get errors again.
