### ISSUE TITLE
Build issue - perl 5.12 really required?

### ISSUE THREAD

**Issue by linsalrob** [ModelSEED/Model-SEED-core#128]
Is perl 5.12 really required (versus 5.10)? 5.10 is the standard on e.g. ubuntu systems and so the build fails.

Rob

**Comment by devoid** [comment]
The truth of the matter is we don't know which perl is required (I
generated the version numbers based on what my system was using). We should
probably change that to perl >= 5.8 or something arbitrarily old.

Also, right now the build system isn't actually _building_ anything; so far
we've just been using it to get dependencies working correctly (with the
help of Carton http://search.cpan.org/~miyagawa/carton-v0.9.3/lib/Carton.pod
)

~ Scott

On Tue, Jan 31, 2012 at 2:24 PM, Rob Edwards <
reply@reply.github.com

**Comment by linsalrob** [comment]
Based on this here is a diff that will work with Ubuntu server 10.10 

diff --git a/Build.PL b/Build.PL
index 6c55317..65fee77 100644
--- a/Build.PL
+++ b/Build.PL
@@ -12,7 +12,7 @@ my $builder = Module::Build->new(
         'Test::More' => 0,
     },
     requires => {
-        'perl' => 5.12,
-        'perl' => 5,
       "Archive::Tar" => 1.54,
       "AutoLoader" => 5.70,
       "Carp" => 1.17,
  @@ -28,14 +28,14 @@ my $builder = Module::Build->new(
       "Fcntl" => 1.06,
       "Rose::DB" => 0,
       "Rose::DB::Object" => 0,
-        "File::Basename" => 2.78,
-        "File::Copy" => 2.18,
-        "File::Basename" => 2.77,
-        "File::Copy" => 2.14,
       "File::Copy::Recursive" => 0.38,
       "File::HomeDir" => 0.98,
       "File::NFSLock" => 1.21,
-        "File::Path" => 2.08_01,
-        "File::Path" => 2.08,
       "File::Temp" => 0.22,
-        "File::stat" => 1.02,
-        "File::stat" => 1.01,
       "FileHandle" => 2.02,
       "Getopt::Long" => 2.38,
       "IO::Socket::INET" => 1.31,
  @@ -54,7 +54,7 @@ my $builder = Module::Build->new(
       "MooseX::Singleton" => 0.27,
       "MooseX::Storage" => 0,
       "MooseX::Storage::Format::JSONpm" => 0,
-        "POSIX" => 1.19,
-        "POSIX" => 1.17,
       "Pod::Usage" => 1.36,
       "SOAP::Lite" => 0.714,
       "Scalar::Util" => 1.23,
  @@ -78,7 +78,7 @@ my $builder = Module::Build->new(
       "integer" => 1.00,
       "lib" => 0.62,
       "namespace::autoclean" => 0.13,
-        "overload" => 1.10,
-        "overload" => 1.07,
       "vars" => 1.01,
   },
   add_to_cleanup      => [ 'ModelSeedCore-*' ],
