### ISSUE TITLE
ms-update setting permissions incorrectly

### ISSUE THREAD

**Issue by aabest** [ModelSEED/Model-SEED-core#136]
I just did an "ms-update" and found that commands weren't running after the update completed:

e.g. running mdl-loadmodel yields a "permission denied" error.

Looking at the bin directory, here are the permissions that are automatically set up:

Turing:~/Desktop/ModelSEED/Model-SEED-core/workspace/public/default> ls -l /Users/student/Desktop/ModelSEED/Model-SEED-core/bin
total 368
-rwxrwxr-x  1 student  staff   384 Feb 23 13:20 CreateDBScheme
-rwxrwxr-x  1 student  staff   202 Feb 23 13:20 ModelDriver
-rwxrwxr-x  1 student  staff   208 Feb 23 13:20 QueueDriver
-rwxr-xr-x  1 student  staff   883 Feb 23 09:55 ReadMe.txt
-rw-rw-r--  1 student  staff   223 Feb 23 13:20 bc-addbiochemistry
-rw-rw-r--  1 student  staff   217 Feb 23 13:20 bc-loadmedia
-rw-rw-r--  1 student  staff   218 Feb 23 13:20 bc-printmedia
-rw-rw-r--  1 student  staff   220 Feb 23 13:20 fba-checkgrowth
-rw-rw-r--  1 student  staff   212 Feb 23 13:20 fba-fva
-rw-rw-r--  1 student  staff   221 Feb 23 13:20 fba-minimalmedia
-rw-rw-r--  1 student  staff   222 Feb 23 13:20 fba-simphenotypes
-rw-rw-r--  1 student  staff   217 Feb 23 13:20 fba-singleko
-rwxrwxr-x  1 student  staff   281 Feb 23 13:20 makeMFAToolkit
-rw-rw-r--  1 student  staff   217 Feb 23 13:20 mdl-addright
-rw-rw-r--  1 student  staff   221 Feb 23 13:20 mdl-autocomplete
-rw-rw-r--  1 student  staff   221 Feb 23 13:20 mdl-changedrains
-rw-rw-r--  1 student  staff   222 Feb 23 13:20 mdl-comparemodels
-rw-rw-r--  1 student  staff   220 Feb 23 13:20 mdl-createmodel
-rw-rw-r--  1 student  staff   220 Feb 23 13:20 mdl-importmodel
-rw-rw-r--  1 student  staff   221 Feb 23 13:20 mdl-inspectstate
-rw-rw-r--  1 student  staff   220 Feb 23 13:20 mdl-loadbiomass
-rw-rw-r--  1 student  staff   218 Feb 23 13:20 mdl-loadmodel
-rw-rw-r--  1 student  staff   220 Feb 23 13:20 mdl-makedbmodel
-rw-rw-r--  1 student  staff   218 Feb 23 13:20 mdl-parsesbml
-rw-rw-r--  1 student  staff   222 Feb 23 13:20 mdl-printcytoseed
-rw-rw-r--  1 student  staff   219 Feb 23 13:20 mdl-printmodel
-rw-rw-r--  1 student  staff   224 Feb 23 13:20 mdl-printmodelgenes
-rw-rw-r--  1 student  staff   218 Feb 23 13:20 mdl-printsbml
-rw-rw-r--  1 student  staff   223 Feb 23 13:20 mdl-reconstruction
-rwxr-xr-x  1 student  staff   105 Jan 11 11:32 ms-build-modules
-rwxr-xr-x  1 student  staff   144 Jan 11 11:32 ms-config
-rw-rw-r--  1 student  staff   218 Feb 23 13:20 ms-createuser
-rw-rw-r--  1 student  staff   218 Feb 23 13:20 ms-deleteuser
-rwxrwxr-x  1 student  staff    78 Feb 23 13:17 ms-goworkspace
-rw-rw-r--  1 student  staff   217 Feb 23 13:20 ms-lasterror
-rw-rw-r--  1 student  staff   221 Feb 23 13:20 ms-listworkspace
-rwxrwxr-x  1 student  staff   221 Feb 23 13:20 ms-load-mysql
-rw-rw-r--  1 student  staff   213 Feb 23 13:20 ms-login
-rw-rw-r--  1 student  staff   214 Feb 23 13:20 ms-logout
-rw-rw-r--  1 student  staff   223 Feb 23 13:20 ms-switchworkspace
-rwxrwxr-x  1 student  staff   106 Feb 23 13:20 ms-update
-rw-rw-r--  1 student  staff   214 Feb 23 13:20 ms-whoami
-rw-rw-r--  1 student  staff   217 Feb 23 13:20 ms-workspace
-rwxrwxr-x  1 student  staff  1551 Feb 23 13:20 source-me.sh
-rw-rw-r--  1 student  staff   220 Feb 23 13:20 sq-blastgenomes
-rw-rw-r--  1 student  staff   220 Feb 23 13:20 util-matrixdist

I manually altered a few... everything works after that. Re-ran the ms-update to see if the permissions issue would occur again... it did.

All of these should be executable, correct?

Thanks,

Aaron

**Comment by jamesclulow** [comment]
yeah, permission are messed up, but just run the following command in your bin directory

chmod +x *

The wildcard will make all files in that directory executable thus solving the problem without having to change each command you want to use manually.

**Comment by aabest** [comment]
Thanks. The file glob approach will work, but is there a more fundamental issue that needs to be addressed, such that this isn't the approach that everyone is expected to take?

**Comment by devoid** [comment]
The attached change should fix it. Run `ms-update` to get the changes.

**Comment by aabest** [comment]
Thanks, Scott. Looks good.
