### ISSUE TITLE
Documentation of file headers

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#14]
There probably should be a short example, perhaps one reaction with several compounds, in two files, to test the model import with.  In addition, there I suggest some accompanying documentation that lists the required headers and formats (even I am still not sure which columns are optional).

**Comment by cshenry** [comment]
Great comment Sam. I definitely agree.... not quite ready to take ownership of this one yet.

**Comment by devoid** [comment]
@samseaver Since you've been using on model-import the most, can you write up this documentation?

**Comment by samseaver** [comment]
Started work on this:

https://bionet.mcs.anl.gov/index.php/Parsing,_importing,_and_printing_models_in_Model_SEED

**Comment by samseaver** [comment]
Done, comments welcome.
