### ISSUE TITLE
Strategies for Biochemistry save() 

### ISSUE THREAD

**Issue by devoid** [ModelSEED/Model-SEED-core#144]
So let's set a baseline here for improving `Biochemistry::save()` performance:

```
my $bio = ModelSEED::MS::Biochemistry->new($data);
$bio->save();

> Init: 23.2144618034363
> Load: 0.00313305854797363
> Save: 168.43293595314
```

So the approach of this save() call:
1. Initialize a rdbo object `Rose::DB::Object->new($data)`
2. Do a speculative load.
3. Save the object.

This is all within a transaction. This is obviously _not good_. So what can we do? Some ideas coming momentarily...

**Comment by samseaver** [comment]
Are the numbers seconds/minutes?

**Comment by devoid** [comment]
Should be fixed with FileDB change.
