### ISSUE TITLE
bc-loadmedia error (MooseDB)

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#145]
Trying to run this command:

./bc-loadmedia -media Succinate-Minimal.MEDIA.MEDIA

resulted in this error:

Error text printed below:

> ModelDriver encountered an unrecoverable error:

 at /Library/Perl/5.10.0/darwin-thread-multi-2level/Moose/Meta/Attribute.pm line 1261for 'Bool' with value 1
        Moose::Meta::Attribute::verify_against_type_constraint('Moose::Meta::Attribute=HASH(0x3131040)', '1\x{d}', 'instance', 'ModelSEED::MooseDB::media=HASH(0x28df920)') called at /Library/Perl/5.10.0/darwin-thread-multi-2level/Moose/Meta/Attribute.pm line 1248
        Moose::Meta::Attribute::_coerce_and_verify('Moose::Meta::Attribute=HASH(0x3131040)', '1\x{d}', 'ModelSEED::MooseDB::media=HASH(0x28df920)') called at /Library/Perl/5.10.0/darwin-thread-multi-2level/Moose/Meta/Attribute.pm line 527
        Moose::Meta::Attribute::initialize_instance_slot('Moose::Meta::Attribute=HASH(0x3131040)', 'Moose::Meta::Instance=HASH(0x28eb080)', 'ModelSEED::MooseDB::media=HASH(0x28df920)', 'HASH(0x28c19d0)') called at /Library/Perl/5.10.0/darwin-thread-multi-2level/Class/MOP/Class.pm line 524
        Class::MOP::Class::_construct_instance('Moose::Meta::Class=HASH(0xf0a8e0)', 'HASH(0x28c19d0)') called at /Library/Perl/5.10.0/darwin-thread-multi-2level/Class/MOP/Class.pm line 497
        Class::MOP::Class::new_object('Moose::Meta::Class=HASH(0xf0a8e0)', 'HASH(0x28c19d0)') called at /Library/Perl/5.10.0/darwin-thread-multi-2level/Moose/Meta/Class.pm line 274
        Moose::Meta::Class::new_object('Moose::Meta::Class=HASH(0xf0a8e0)', 'HASH(0x28c19d0)') called at /Library/Perl/5.10.0/darwin-thread-multi-2level/Moose/Object.pm line 28
        Moose::Object::new('ModelSEED::MooseDB::media', 'HASH(0x28c19d0)') called at /Users/seaver/Software/ModelSEEDcore/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 355
        ModelSEED::FIGMODEL::FIGMODELdatabase::create_moose_object('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x286b6e0)', 'media', 'HASH(0x28c19d0)') called at /Users/seaver/Software/ModelSEEDcore/lib/ModelSEED/ModelDriver.pm line 1583
        ModelSEED::ModelDriver::bcloadmedia('ModelSEED::ModelDriver=HASH(0x286b510)', 'bcloadmedia', 'HASH(0x286b540)') called at /Users/seaver/Software/ModelSEEDcore/lib/ModelSEED/ModelDriver.pl line 131
        main::__ANON__() called at /Library/Perl/5.10.0/Try/Tiny.pm line 76
        eval {...} called at /Library/Perl/5.10.0/Try/Tiny.pm line 67
        Try::Tiny::try('CODE(0x28c3e00)', 'Try::Tiny::Catch=REF(0x286b4a0)') called at /Users/seaver/Software/ModelSEEDcore/lib/ModelSEED/ModelDriver.pl line 135
        require /Users/seaver/Software/ModelSEEDcore/lib/ModelSEED/ModelDriver.pl called at /Users/seaver/Software/ModelSEEDcore/config//ModelSEEDbootstrap.pm line 23
        main::run() called at -e line 3

**Comment by samseaver** [comment]
Despite the recent MooseDB fixes, this error still exists

**Comment by devoid** [comment]
Can you try this again? I think today's change may have fixed it.

**Comment by samseaver** [comment]
Yea, it works now. Thanks.
