### ISSUE TITLE
Compilation Issues (New Interface)

### ISSUE THREAD

**Issue by devoid** [ModelSEED/Model-SEED-core#146]
Ok, so removing the "parent" attribute did not fix the issue. Errors simply "move down" to the has "uuid" attribute. I think this has to do with how the `use package` statements are done.

@cshenry

**Comment by cshenry** [comment]
I found a number of bugs in the moose objects, but all have been corrected, and the objects now compile. This is demonstrated with the now successfully running test "SEEDFactory.t"
