### ISSUE TITLE
mdl-loadbiomass has stopped working

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#154]
If I run this:

./mdl-loadbiomass -biomass bio12477 -model FlatAraRecon.45632

I now get this:

> ModelDriver encountered an unrecoverable error:

```
""Creating new object failed."" at /home/seaver/ModelSEEDCore/lib/ModelSEED/utilities.pm line 97
    ModelSEED::utilities::ERROR('Creating new object failed.') called at /home/seaver/ModelSEEDCore/lib/PPO/DBObject.pm line 370
    DBObject::set_attributes('ModelSEED::ModelDB::REACTION_MODEL=HASH(0x7dd32b0)', 'HASH(0x7da5888)') called at /home/seaver/ModelSEEDCore/lib/PPO/DBObject.pm line 239
    DBObject::create('ModelSEED::ModelDB::REACTION_MODEL=HASH(0x7dd32b0)', 'HASH(0x7da5888)') called at /home/seaver/ModelSEEDCore/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 239
    ModelSEED::FIGMODEL::FIGMODELdatabase::create_object('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x8027c00)', 'rxnmdl', 'HASH(0x7da5888)') called at /home/seaver/ModelSEEDCore/lib/ModelSEED/FIGMODEL/FIGMODELmodel.pm line 1668
    ModelSEED::FIGMODEL::FIGMODELmodel::biomassReaction('ModelSEED::FIGMODEL::FIGMODELmodel=HASH(0x8025988)', 'bio12477') called at /home/seaver/ModelSEEDCore/lib/ModelSEED/ModelDriver.pm line 2544
    ModelSEED::ModelDriver::mdlloadbiomass('ModelSEED::ModelDriver=HASH(0x7d98208)', 'mdlloadbiomass', 'HASH(0x7da5d68)') called at /home/seaver/ModelSEEDCore/lib/ModelSEED/ModelDriver.pl line 131
    main::__ANON__() called at /vol/model-prod/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Try/Tiny.pm line 76
    eval {...} called at /vol/model-prod/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x7f177a8)', 'Try::Tiny::Catch=REF(0x7d98178)') called at /home/seaver/ModelSEEDCore/lib/ModelSEED/ModelDriver.pl line 135
    require /home/seaver/ModelSEEDCore/lib/ModelSEED/ModelDriver.pl called at /home/seaver/ModelSEEDCore/config//ModelSEEDbootstrap.pm line 24
    main::run() called at -e line 3
```

> Model-SEED-core revision: 239f778da74ee80cd0ed20fc274730304e4b4224

The hash attributes that is being passed in FIGMODELmodel::biomassReaction looks like this:

```
$self->db()->create_object("rxnmdl",{
                            MODEL=>$self->id(),
                            REACTION=>$newBiomass,
                            compartment=>"c",
                            confidence=>1,
                            pegs=>"SPONTANEOUS",
                            directionality=>"=>"
                    })
```

**Comment by samseaver** [comment]
I figured out that this was an interesting case of the code not removing old biomass reactions, and when I went back to a previous one, it rejected it because it was already in the REACTION_MODEL table, along with 5 other biomass reactions.

However, when I deleted the biomass reactions for my model in the database directly, I still got this error message:

> ModelDriver encountered an unrecoverable error:

```
Can't call method "database" on an undefined value at /home/seaver/ModelSEEDCore/lib/ModelSEED/FIGMODEL/FIGMODELdata.pm line 48.
```

> Model-SEED-core revision: cd06ebeb5fa5971556edf62f4d90fc56b1a5fdbb

The biomass reaction was still inserted correctly into the database though.

**Comment by samseaver** [comment]
OK, here's more data: 

The whole thing falls apart in FIGMODELmodel when doing this:

```
            $self->ppo()->biomassReaction($newBiomass)
```

So, it's unable to update its own PPO object.  The result is that there's no synchrony between the biomass reaction in the REACTION_MODEL table and the biomass reaction in the MODEL table, and thereafter, I get weird errors.

**Comment by cshenry** [comment]
This bug was introduced in commits:
2571b588c4e7da1de14409a520a0908df8917315
When this line was added to FIGMODEL->new():
ModelSEED::globals::SETFIGMODEL($self);
You absolutely positively cannot do this in FIGMODEL->new(). I understand this was introduced to solve a bug, but it must be solved a different way. If you do this in FIGMODEL->new(), the global FIGMODEL is reset everytime you create a new FIGMODEL, and very very bad things happen.
