### ISSUE TITLE
Move issue tracking repo to ModelSeed

### ISSUE THREAD

**Issue by devoid** [ModelSEED/Model-SEED-core#16]
I hate having to commit to chris's repository to make changes. I've created a [ModelSEED organization](https://github.com/organizations/ModelSEED).

Chris, you need to [move your repo](http://help.github.com/move-a-repo/) over to the organization and fork a new copy from it. This way you'll have your own copy with your own master back.

**Comment by cshenry** [comment]
Okay. The Model SEED repository has been moved to the Organization site as suggested. I created a new "team" on that site called collaborators, and I put Raphy and his colleage in that team. Hopefully they're still getting these "issue" notifications. I'll send Raphy to separate email to make sure.
