### ISSUE TITLE
missing Model-SEED-core/bin/configureModelSEED.sh file

### ISSUE THREAD

**Issue by raphyz** [ModelSEED/Model-SEED-core#20]
Just moved to ModelSEED / Model-SEED-core  and did the git clone command, and I do not find Model-SEED-core/bin/configureModelSEED.sh file.

**Comment by devoid** [comment]
I've renamed this to ms-config. The interface is:

```
./bin/ms-config load config/Settings.conf
./bin/ms-config unload
./bin/ms-config reload Settings.conf
```

Settings.conf is a little cleaner and some of the _unnecessary_ "required parameters" have been removed.

**Comment by devoid** [comment]
See `./bin/ms-config --help` for documentation on use. I've added a `--fast` flag and a `clean` command.
