### ISSUE TITLE
ClientThing attempts to contact defunct server?!?

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#25]
This has just come up, and I can no longer run my model imports.  The error I'm getting is a "500" error returned by ClientThing because it's trying to contact:

http://bioseed.mcs.anl.gov/~chenry/FIG/CGI/FBAMODEL_server.cgi

1) I don't know why its doing this, but this cant be integral to model import
2) If you visit this website, you'll see that some perl modules have gone missing...

**Comment by devoid** [comment]
Sam,

Can you give me a sense as to what you're calling for your import scripts?
Then I can track down the bugs for this and the other open issues.

~ Scott

**Comment by samseaver** [comment]
I'm running the importmodel function via bin/ModelDriver:

bin/ModelDriver importmodel?MetaCyc?3702.9?seaver?/Users/seaver/Documents/Projects/Model_Import_Files/

You can find some sample model files that had previously worked in:

/vol/model-dev/MODEL_DEV_DB/ReactionDB/ImportFiles/

**Comment by samseaver** [comment]
This issue has been fixed by Chris's latest commit so I'm closing it
