### ISSUE TITLE
Can't find biomass on import

### ISSUE THREAD

**Issue by aabest** [ModelSEED/Model-SEED-core#27]
Could not find new biomass reaction bio00001 at /Users/best/ModelSEED/lib/ModelSEED/FIGMODEL.pm line 137
    ModelSEED::FIGMODEL::FIGMODELWARNING('Could not find new biomass reaction bio00001') called at /Users/best/ModelSEED/lib/ModelSEED/FIGMODEL/FIGMODELmodel.pm line 1587
    ModelSEED::FIGMODEL::FIGMODELmodel::biomassReaction('ModelSEED::FIGMODEL::FIGMODELmodel=HASH(0xd31ec0)', 'bio00001') called at /Users/best/ModelSEED/lib/ModelSEED/FIGMODEL.pm line 2648
    ModelSEED::FIGMODEL::import_model('ModelSEED::FIGMODEL=HASH(0xcf2170)', 'HASH(0x815550)') called at /Users/best/ModelSEED/lib/ModelSEED/ModelDriver.pm line 4043
    ModelSEED::ModelDriver::importmodel('ModelSEED::ModelDriver=HASH(0x8153c0)', 'importmodel', 'HASH(0xd47e00)') called at /Users/best/ModelSEED/lib/ModelSEED/ModelDriver.pl line 61
    require /Users/best/ModelSEED/lib/ModelSEED/ModelDriver.pl called at /Users/best/ModelSEED/config//ModelSEEDbootstrap.pm line 24
    main::run() called at -e line 3
Failure running /Users/best/ModelSEED/lib/ModelSEED/ModelDriver.pl: Can't call method "public" on an undefined value at /Users/best/ModelSEED/lib/ModelSEED/FIGMODEL/FIGMODELmodel.pm line 659.

**Comment by cshenry** [comment]
I _believe_ this bug has been corrected.
