### ISSUE TITLE
Can't run classifyreactions

### ISSUE THREAD

**Issue by mdejongh** [ModelSEED/Model-SEED-core#28]
~/Desktop/ModelSEED/Model-SEED-core/bin> ModelDriver classifyreactions?iJR904.3?Complete?0?0

Processing argument: classifyreactions?iJR904.3?Complete?0?0
Use of uninitialized value in pattern match (m//) at /Users/dejongh/Desktop/ModelSEED/Model-SEED-co\
re/lib/PPO/DBObject.pm line 495.
Now processing model: iJR904.3
/Users/dejongh/Desktop/ModelSEED/Model-SEED-core/software/mfatoolkit/bin/mfatoolkit resetparameter \
"MFA input directory" /Users/dejongh/Desktop/ModelSEED/Model-SEED-core/data/ReactionDB/ parameterfi\
le "../Parameters/ProductionMFA.txt" parameterfile "/Users/dejongh/Desktop/ModelSEED/Model-SEED-cor\
e/data/ReactionDB/MFAToolkitOutputFiles/2098263/FluxVariabilityAnalysis.txt" parameterfile "/Users/\
dejongh/Desktop/ModelSEED/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/2098263/AddnlFBAPar\
ameters.txt" LoadCentralSystem "/Users/dejongh/Desktop/ModelSEED/Model-SEED-core/data/ReactionDB/MF\
AToolkitOutputFiles/2098263/iJR904.3.tbl" > "/Users/dejongh/Desktop/ModelSEED/Model-SEED-core/logs/\
fba-2098263.log"
StringDBTable:loadFromFile:could not open table file
StringDBTable:loadFromFile:could not open table file
mkdir: /scratch: No such file or directory
cp: /scratch/2098263: No such file or directory
FIGMODELfba:parseTightBounds:could not find tight bound results file
SUCCESS:
FAIL:iJR904.3;

**Comment by cshenry** [comment]
So I decided to create a new more general function called "fbafva". This function allows you to specify a model, media condition, list of variables to be minimized and maximized, some general options, a filename for output, and flags indicating if results should be saved in the database. By default, the variables minimized and maximized are flux and uptake.

The function prints output to an excel file, although output to text remains an option. We'll be documenting in the wiki shortly.

**Comment by mdejongh** [comment]
Chris - what parameters/values should I use to duplicate what classifyreactions does?
