### ISSUE TITLE
problem with sandbox install on biologin-4

### ISSUE THREAD

**Issue by mdejongh** [ModelSEED/Model-SEED-core#29]
dejongh@biologin-4:~/Model-SEED-core$ /vol/model-prod/env/config.sh: line 2: /home/dejongh/Model-SEED-core/Model-SEED-core/bin/ms-config: No such file or directory

[2]+  Exit 127                /vol/model-prod/env/install.sh /home/dejongh/Model-SEED-core  (wd: ~)

**Comment by jplfaria** [comment]
Should work fine now! 
Give it a shot, reopen if needed.
