### ISSUE TITLE
SQLite error during import model

### ISSUE THREAD

**Issue by jplfaria** [ModelSEED/Model-SEED-core#31]
[PPOBackend.pm 244]Database error: DBD::SQLite::db prepare failed: no such column: defaultStudyMedia at /Users/jplfaria/Model-SEED-core/lib/PPO/PPOBackend.pm line 226.

**Comment by devoid** [comment]
I recommend doing a git pull for new changes, deleting `data/TestDB.tgz`, `data/TestData/`, and `data/ModelDB`. Then download `data/ModelDB` from http://bioseed.mcs.anl.gov/~devoid/ModelDB-sqlite.tgz and running:

```
tar -xzf ModelDB-sqlite.tgz -C `path/to/data`
```

Closing, works for me. Reopen if it is still an issue.

**Comment by jplfaria** [comment]
I don't have permission to re-open the issue!

Now there's is this issue of not finding roles any roles:
Since there is such a huge amount (way more then the ones I post bellow) of roles not being found I assume, none of the roles are being found (or maybe wrong :/)
....
...
FIGMODELrole:?:Could not find role in database:GnsA protein
FIGMODELrole:?:Could not find role in database:Secretion monitor precursor
FIGMODELrole:?:Could not find role in database:TorCAD operon transcriptional
regulatory protein TorR
FIGMODELrole:?:Could not find role in database:Chaperone protein TorD
FIGMODELrole:?:Could not find role in database:Putative cytoplasmic protein
FIGMODELrole:?:Could not find role in database:Flavoprotein wrbA
FIGMODELrole:?:Could not find role in database:Conidiation-specific protein
10
Found:cpd00201 for 10fthf
Found:cpd11423 for 12dgr_EC
Found:cpd00453 for 12ppd-S
Found:cpd00203 for 13dpg
Found:cpd01155 for 15dap
Found:cpd02431 for 1pyr5c

Don't know if that was expected to happen!

**Comment by devoid** [comment]
1. You should have permission now.
2. I'm seeing 11,250 roles in the SQLite ROLE table. What function are you calling.

**Comment by jplfaria** [comment]
I don't have that error anymore, you fixed it, thanks!
I am just calling the importmodel function: 
./importmodel -name iJR904 -genome 83333.1 -owner jplfaria -overwrite 1

Now the only issue keeping from successfully importing a model is the one I reported issue #32.

**Comment by samseaver** [comment]
Actually, this issue with roles has occurred for me everytime I use a new genome id.  When the code first fetches the genome statistics from Sapling/RAST/PubSeed, it then spurges all the roles.  Thereafter, it doesn't do it again as the stats have been compiled.  Jose, if you used a different genome id, you should get the same error again, not sure what it is.

**Comment by samseaver** [comment]
I'm making this a separate issue...

**Comment by jplfaria** [comment]
You're right Sam, I tried with the Bacillus genome and got the "could not find roles" error again.
