### ISSUE TITLE
Error encountered at the end of model import (using SQLite)

### ISSUE THREAD

**Issue by jplfaria** [ModelSEED/Model-SEED-core#32]
Found:rxn00191 for ALATA_L
Found:rxn00283 for ALAR !!!!!!!!!!!!!!!!!!!!!!!!!!!
Found:rxn00342 for ASNN
Found:rxn00340 for ASNS2
Found:rxn00416 for ASNS1
Found:rxn00347 for ASPT
Found:rxn00260 for ASPTA
Found:rxn00904 for VPAMT
Found:rxn08291 for DAAD
Found:rxn00283 for ALARi !!!!!!!!!!!!!!!!!!!!!!!!!
Failure running /Users/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pl: Creating new object failed. at /Users/jplfaria/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 132
    ModelSEED::FIGMODEL::FIGMODELERROR('Creating new object failed.') called at /Users/jplfaria/Model-SEED-core/lib/PPO/DBObject.pm line 370
    DBObject::set_attributes('ModelSEED::ModelDB::REACTION_MODEL=HASH(0x7fa154a09390)', 'HASH(0x7fa13c5057d8)') called at /Users/jplfaria/Model-SEED-core/lib/PPO/DBObject.pm line 239
    DBObject::create('ModelSEED::ModelDB::REACTION_MODEL=HASH(0x7fa154a09390)', 'HASH(0x7fa13c5057d8)') called at /Users/jplfaria/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 232
    ModelSEED::FIGMODEL::FIGMODELdatabase::create_object('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x7fa13d844150)', 'rxnmdl', 'HASH(0x7fa13c5057d8)') called at /Users/jplfaria/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 2840
    ModelSEED::FIGMODEL::import_model('ModelSEED::FIGMODEL=HASH(0x7fa13c068ff8)', 'HASH(0x7fa13c0e7368)') called at /Users/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pm line 4043
    ModelSEED::ModelDriver::importmodel('ModelSEED::ModelDriver=HASH(0x7fa13a02f168)', 'importmodel', 'HASH(0x7fa13a30d568)') called at /Users/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 61
    require /Users/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pl called at /Users/jplfaria/Model-SEED-core/config//ModelSEEDbootstrap.pm line 24
    main::run() called at -e line 3

**Comment by cshenry** [comment]
When the same reaction appears in the same compartment multiple times in a model with different directionality, the system would throw an error. This has now been fixed such that the two reactions are combined with the most inclusive directionality.
