### ISSUE TITLE
Build issue with MFAToolkit in Bio-enviornment

### ISSUE THREAD

**Issue by devoid** [ModelSEED/Model-SEED-core#33]
EM -c ../Source/driver.cpp; mv _.o ../Source
../Source/driver.cpp:22:24: error: MFAToolkit.h: No such file or directory
../Source/driver.cpp:124:3: warning: no newline at end of file
../Source/driver.cpp: In function 'int main(int, char__)':
../Source/driver.cpp:27: error: 'SetProgramPath' was not declared in this scope
../Source/driver.cpp:28: error: 'SetParameter' was not declared in this scope
../Source/driver.cpp:31: error: 'STATIC_INPUT_FILE' was not declared in this scope
../Source/driver.cpp:31: error: 'SetInputParametersFile' was not declared in this scope
../Source/driver.cpp:32: error: 'LoadParameters' was not declared in this scope
../Source/driver.cpp:32: error: 'FAIL' was not declared in this scope
../Source/driver.cpp:35: error: 'ClearParameterDependance' was not declared in this scope
../Source/driver.cpp:36: error: 'Initialize' was not declared in this scope
../Source/driver.cpp:36: error: 'FAIL' was not declared in this scope
../Source/driver.cpp:39: error: 'LoadFIGMODELParameters' was not declared in this scope
../Source/driver.cpp:41: error: 'DriverOptions' was not declared in this scope
../Source/driver.cpp:43: error: 'vector' was not declared in this scope
../Source/driver.cpp:43: error: 'string' was not declared in this scope
../Source/driver.cpp:43: error: 'Arguments' was not declared in this scope
../Source/driver.cpp:45: error: expected `;' before 'Buff'
../Source/driver.cpp:46: error: 'Buff' was not declared in this scope
../Source/driver.cpp:48: error: 'CommandlineInterface' was not declared in this scope
../Source/driver.cpp:51: error: 'Cleanup' was not declared in this scope
../Source/driver.cpp:54: error: 'string' was not declared in this scope
../Source/driver.cpp:54: error: expected`;' before 'OutputPath'
../Source/driver.cpp:55: error: 'OutputPath' was not declared in this scope
../Source/driver.cpp:56: error: 'GetParameter' was not declared in this scope
../Source/driver.cpp:58: error: 'GetDatabaseDirectory' was not declared in this scope
../Source/driver.cpp:58: error: 'system' was not declared in this scope
../Source/driver.cpp:60: error: 'GetDatabaseDirectory' was not declared in this scope
../Source/driver.cpp:60: error: 'system' was not declared in this scope
../Source/driver.cpp: In function 'void DriverOptions()':
../Source/driver.cpp:69: error: 'cout' was not declared in this scope
../Source/driver.cpp:69: error: 'endl' was not declared in this scope
../Source/driver.cpp:78: error: 'AskNum' was not declared in this scope
../Source/driver.cpp:82: error: 'LoadDatabaseFile' was not declared in this scope
../Source/driver.cpp:86: error: 'ProcessDatabase' was not declared in this scope
../Source/driver.cpp:93: error: 'ProcessWebInterfaceModels' was not declared in this scope
mv: cannot stat `_.o': No such file or directory
make: **\* [../Source/driver.o] Error 1
No user account found with name: !

**Comment by samseaver** [comment]
I had to export an environmental variable that wasn't added to the config files, something like 
`export MODEL_SEED_CORE=/home/seaver/ModelSEEDCore/`

and this fixed my issues (I had different issues because my MFAToolkit had already been compiled).

**Comment by samseaver** [comment]
In the latest update of the git repository, on biologin-4, running:

`/vol/model-prod/env/config.sh .`

in /home/seaver/ModelSEEDCore crashed with these errors in making MFAToolkit:

g++: CoreFoundation: No such file or directory
g++: IOKit: No such file or directory

**Comment by samseaver** [comment]
This works for me now so I'm closing this issue for the time being.
