### ISSUE TITLE
Roles not recognized first time a genome id is used

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#34]
If a genome id is first used upon import, the server fetches the genome statistics from Sapling/RAST/PubSeed and then spurges out a long list of errors for every role that _could_ be in the local database, possibly because not every role is in the downloaded SQL database (is it?)

In any case, the model import proceeds fine, and doesn't show the error again if the same genome id is used again because the statistics had already been compiled.

To reproduce the error, the corresponding row from the GENOMESTATS table must be removed.

**Comment by devoid** [comment]
Based on my tests this afternoon, all of the roles in the "main" ModelDB are
in the SQLite copies. I cannot say anything for the MySQL ones, but I think
Jos is using SQLite so it's probably not an issue of "missing" roles.

I don't know the answer, though. I'll have to familiarize myself with model
import a bit.

~ Scott

**Comment by cshenry** [comment]
I believe this issue was resolved.
