### ISSUE TITLE
Function on importmodel still goes after dbd:mysql (after loading reactions) [Using SQLite]

### ISSUE THREAD

**Issue by jplfaria** [ModelSEED/Model-SEED-core#36]
Found:rxn00806 for LEUTAi
Found:rxn00902 for IPPS
Found:rxn03062 for IPMD
Found:rxn01208 for OMCDC
Found:rxn02811 for IPPMIa
Found:rxn02789 for IPPMIb
Failure running /Users/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pl: install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (@INC contains: /Users/jplfaria/Model-SEED-core/lib /Users/jplfaria/Model-SEED-core/lib/FigKernelPackages /Users/jplfaria/Model-SEED-core/lib/myRAST /Users/jplfaria/Model-SEED-core/lib/PPO /Users/jplfaria/Model-SEED-core/config/ /opt/local/lib/perl5/site_perl/5.12.3/darwin-multi-2level /opt/local/lib/perl5/site_perl/5.12.3 /opt/local/lib/perl5/vendor_perl/5.12.3/darwin-multi-2level /opt/local/lib/perl5/vendor_perl/5.12.3 /opt/local/lib/perl5/5.12.3/darwin-multi-2level /opt/local/lib/perl5/5.12.3 /opt/local/lib/perl5/site_perl /opt/local/lib/perl5/vendor_perl .) at (eval 1946) line 3.
Perhaps the DBD::mysql perl module hasn't been fully installed,
or perhaps the capitalisation of 'mysql' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Proxy, SQLite, Sponge.
 at /Users/jplfaria/Model-SEED-core/lib/PPO/PPOBackend/MySQL.pm line 61

**Comment by cshenry** [comment]
This was an error related to the checkout of new IDs for the biomass reaction. This failed because this code assumed a mysql server. The problem has now been fixed.
