### ISSUE TITLE
ModelDriver Catch die()s and report in a nicer way

### ISSUE THREAD

**Issue by devoid** [ModelSEED/Model-SEED-core#37]
Right now if a routine called by ModelDriver `die`s it does not report a "user friendly" error message. We can fix this by `catch`ing the error, parsing out the actual error message and displaying it to the user along with the suggestion to submit the detailed error log (the stack trace) to this ticket repository.

**Comment by cshenry** [comment]
So if I understand, we catch the error, print the error message, drop the full stack trace into an error log, and print a note suggesting the content of the log be posted as an issue in github.

Perhaps we keep just one error log kind of like apache? Keep it in the logs directory? append entries with a time stamp so you can easily tell when the error showed up?

All this sounds good to me, and simple to implement.
