### ISSUE TITLE
CPLEX entires error on makefile (bioenvironment)

### ISSUE THREAD

**Issue by jplfaria** [ModelSEED/Model-SEED-core#38]
When I load the ms config file (bin directory, bioenvironment):

[jplfaria@biologin-4 bin]$ ./ms-config load

I run into this error:

g++ -O3 -fPIC -fexceptions -DNDEBUG -DIL_STD -DILOSTRICTPOD -DLINUX -I/vol/model-prod/Software/solvers/cplex/include/ilcplex/ -I/vol/model-prod/Software/solvers/glpk-4.38/include -I../Include -DNOSAFEMEM -DNOBLOCKMEM -o mfatoolkit ../Source/driver.o ../Source/MFAProblem.o ../Source/CPLEXapi.o ../Source/SCIPapi.o ../Source/GLPKapi.o ../Source/LINDOapiEMPTY.o ../Source/SolverInterface.o ../Source/Species.o ../Source/Data.o ../Source/InterfaceFunctions.o ../Source/Identity.o ../Source/Reaction.o ../Source/GlobalFunctions.o ../Source/AtomCPP.o ../Source/UtilityFunctions.o ../Source/AtomType.o ../Source/Gene.o ../Source/GeneInterval.o ../Source/stringDB.o -L/vol/model-prod/Software/solvers/glpk-4.38/src/.libs -lglpk -L/home/chenry/Software/CPLEX_Studio_AcademicResearch122/cplex/lib/x86-64_sles10_4.1/static_pic -lcplex -lm -lpthread -lz -framework CoreFoundation -framework IOKit
g++: CoreFoundation: No such file or directory
g++: IOKit: No such file or directory
make: **\* [MFATOOLKIT] Error 1

Those entires in the make file should only appear when cplex is being used on OSX. Otherwise, they should be removed.

José

**Comment by samseaver** [comment]
This error has since been fixed.  CoreFoundation and IOKit are Max OS X 'frameworks' that were left in the makefile for the BIO environment.

**Comment by jplfaria** [comment]
yes Sam.
Me and Chris spent a couple of hours fixing the makefile and works fine now!
