### ISSUE TITLE
problem importing a model

### ISSUE THREAD

**Issue by raphyz** [ModelSEED/Model-SEED-core#39]
Hi

Just run the command listed in wiki :./importmodel -name "iJR904" -genome "83333.1"  after login
and got 
Processing argument: importmodel
Found:cpd00201 for 10fthf
Found:cpd11423 for 12dgr_EC
....
Found:rxn02811 for IPPMIa
Found:rxn02789 for IPPMIb
Whoops! We encountered an unrecoverable error.

Creating new object failed.

A complete log of the problem has been printed to:

/home/raphyz/Desktop/SHARE/phd/Model-SEED-core/.errors/error-ei5dc

this log file content is:

> ModelDriver encountered an unrecoverable error:

""Creating new object failed."" at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 133
    ModelSEED::FIGMODEL::FIGMODELERROR('Creating new object failed.') called at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/PPO/DBObject.pm line 370
    DBObject::set_attributes('ModelSEED::ModelDB::REACTION_MODEL=HASH(0x1e389008)', 'HASH(0x99a94b0)') called at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/PPO/DBObject.pm line 239
    DBObject::create('ModelSEED::ModelDB::REACTION_MODEL=HASH(0x1e389008)', 'HASH(0x99a94b0)') called at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 232
    ModelSEED::FIGMODEL::FIGMODELdatabase::create_object('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x4b9c900)', 'rxnmdl', 'HASH(0x99a94b0)') called at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 2830
    ModelSEED::FIGMODEL::import_model('ModelSEED::FIGMODEL=HASH(0x2e6ed10)', 'HASH(0x3009a28)') called at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/ModelSEED/ModelDriver.pm line 3959
    ModelSEED::ModelDriver::importmodel('ModelSEED::ModelDriver=HASH(0x2e6f058)', 'importmodel', 'HASH(0x300d498)') called at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 121
    main::**ANON**() called at /usr/lib64/perl5/vendor_perl/5.12.3/Try/Tiny.pm line 76
    eval {...} called at /usr/lib64/perl5/vendor_perl/5.12.3/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x2e6f0b8)', 'Try::Tiny::Catch=REF(0x2e66b00)') called at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 124
    require /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/ModelSEED/ModelDriver.pl called at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/config//ModelSEEDbootstrap.pm line 27
    main::run() called at -e line 3

**Comment by raphyz** [comment]
the second time running the command with -overwrite 1 ended well.
It might be an internet problem. Is there a way for you to identify this, and send an error message pointing to that?

**Comment by jamesclulow** [comment]
Had the same problem as well raphyz. Trying a second time with -overwrite 1 to see if it works.

**Comment by jamesclulow** [comment]
Yep, worked the second time around with -overwrite 1. Seems to get hung up on the biomass equation the first time (No idea why...)

**Comment by devoid** [comment]
I think this is now fixed with a recent update (a678e6a7377cc0430201725382935360a33145d8). Feel free to reopen this issue if you continue to have problems.
