### ISSUE TITLE
Problem with MySQL socket

### ISSUE THREAD

**Issue by cshenry** [ModelSEED/Model-SEED-core#4]
OK, I still got the DB error:

```
Failure running
/Users/seaver/Software/Model-SEED-core/lib/ModelSEED/ModelDriver.pl:
DBI connect('database=ModelDB;host=localhost;port=3306;mysql_socket=/var/lib/mysql/mysql.sock','ModelSEED',...)
failed: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) at /Users/seaver/Software/Model-SEED-core/lib/PPO/PPOBackend/MySQL.pm
line 82
```

As it turns out, the code in `lib/PPO/PPOBackend/MySQL.pm` is genuinely trying to connect through the socket at `/var/lib/mysql/mysql.sock` whereas on my mac, the MySQL installation runs the socket at `/tmp/mysql.sock`

so this command:

```
sudo ln -s /tmp/mysql.sock /var/lib/mysql/mysql.sock
```

fixed the problem, so that's probably another line needed for the instructions, that the code assumes the socket is placed at `/var/lib/mysql`, and a soft link may be needed to fix this.

**Comment by devoid** [comment]
This is obviously a configurable. But it's accessible from `mysql-admin` so we could conceivably have a script to discover it. It isn't high priority though.

**Comment by devoid** [comment]
Now able to set this in `config/Settings.conf` with:

```
[Database]
socket=/path/to/mysql.sock
```
