### ISSUE TITLE
would be nice if commands had a usage message

### ISSUE THREAD

**Issue by raphyz** [ModelSEED/Model-SEED-core#40]
It would be nice if the command lines would have a usage message for example:

./importmodel --help

or -?

I had to guess that for importmodel the -overwrite parameter expects a 0|1 and not yes|no or something else
the usage messge should list that

**Comment by cshenry** [comment]
It's a good point, and I agree. although, if you type "./importmodel" or any other function with no arguments, a usage message does appear. It's not a great usage message, but it's something. 

Eventually we will do as you day... I suspect it will involve porting in the argument descriptions from the wiki into the code in some form.

**Comment by raphyz** [comment]
Sorry, I have seen the message, but I did not understand it was a usage
message...

**Comment by cshenry** [comment]
I tried to make the usage function better.
