### ISSUE TITLE
printmodelfiles issues

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#42]
In the BIO environment, it didn't print these files out locally, only in a pre-specified location:

/vol/model-dev/MODEL_DEV_DB/MSModelFiles/iJR904.tbl
/vol/model-dev/MODEL_DEV_DB/MSModelFiles/bio00320.txt

In the local environment, it didn't recognize my unique SEED ID, even if I "log in" so I had to append it to the model name.

Finally, it's expecting the biochemistry data to be in the database rather than in the flat files, because I get this error:

"Cannot obtain ppo data for reaction"

**Comment by samseaver** [comment]
Update:

In the BIO environment, if I run:

`./bin/printmodelfiles -model "iJR904"`

It works, however:

`./bin/printmodelfiles -model "iAF1260"`

fails, again, with a "Cannot obtain ppo data for reaction" error

**Comment by devoid** [comment]
According to the ModelDB database, there is no biomass reaction associated with the model. I've fixed this so that the code will output the model with no biomass file.
