### ISSUE TITLE
loadmodelfromfile issues

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#43]
I've not tried this in the BIO environment, but locally:

1) The -biomass parameter doesn't work, it keeps looking in the same location (./data/MSModelFiles)

2) The -filename parameter works, but if it is not used, then the filename that it looks for _must_ have the user index in the filename, ie:

`data/MSModelFiles/iJR904.45632.tbl1`

instead of 

`data/MSModelFiles/iJR904.tbl`

3) The overwrite function works for sake of documentation, but if the script fails the first time (ie can't find biomass file) it doesn't roll back the inserted data, so the next time you run it, even though it "failed" you still have to overwrite.  This can be confusing.

**Comment by tammyk** [comment]
Whenever I try to load my model it says it "could not find biomass specification file" (even tho the biomass file is in MSModelFiles and I even load it to the database before loading the model). I was wondering where I can find the user index number, so maybe if I try to include the path with the user index it would work.

**Comment by samseaver** [comment]
No longer an issue
