### ISSUE TITLE
error using loadmodelfromfile

### ISSUE THREAD

**Issue by mdejongh** [ModelSEED/Model-SEED-core#45]
I scp'ed my iYusMp.149 model from bio\* to my desktop, then ran

bin/loadmodelfromfile -name "iYusMp.149" -genome "272634.1"

Got the following error log (note that the id used below has an extra ".149" on it)

> ModelDriver encountered an unrecoverable error:

""Could not find model specification file: /Users/dejongh/Desktop/ModelSEED/Model-SEED-core/data/MS\
ModelFiles/iYusMp.149.149.tbl!"" at /Users/dejongh/Desktop/ModelSEED/Model-SEED-core/lib/ModelSEED/\
FIGMODEL.pm line 133
        ModelSEED::FIGMODEL::FIGMODELERROR('Could not find model specification file: /Users/dejongh\
/Deskt...') called at /Users/dejongh/Desktop/ModelSEED/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm li\
ne 2545
        ModelSEED::FIGMODEL::import_model_file('ModelSEED::FIGMODEL=HASH(0x7fbcac03fe50)', 'HASH(0x\
7fbcae21a6b0)') called at /Users/dejongh/Desktop/ModelSEED/Model-SEED-core/lib/ModelSEED/ModelDrive\
r.pm line 4513
        ModelSEED::ModelDriver::loadmodelfromfile('ModelSEED::ModelDriver=HASH(0x7fbcac040198)', 'l\
oadmodelfromfile', 'HASH(0x7fbcae21a5c0)') called at /Users/dejongh/Desktop/ModelSEED/Model-SEED-co\
re/lib/ModelSEED/ModelDriver.pl line 121
        main::**ANON**() called at /System/Library/Perl/Extras/5.12/Try/Tiny.pm line 76
        eval {...} called at /System/Library/Perl/Extras/5.12/Try/Tiny.pm line 67
        Try::Tiny::try('CODE(0x7fbcac0401f8)', 'Try::Tiny::Catch=REF(0x7fbcae1a41d0)') called at /U\
sers/dejongh/Desktop/ModelSEED/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 124
        require /Users/dejongh/Desktop/ModelSEED/Model-SEED-core/lib/ModelSEED/ModelDriver.pl calle\
d at /Users/dejongh/Desktop/ModelSEED/Model-SEED-core/config//ModelSEEDbootstrap.pm line 26
        main::run() called at -e line 3

I reran using 

bin/loadmodelfromfile -name "iYusMp" -genome "272634.1"

and didn't get any errors log, but did get the following message:

Processing argument: loadmodelfromfile
Adding new model iYusMp.149 for mdejongh into database
 [PPOBackend.pm 246]Database error: DBD::mysql::st execute failed: Unknown column 'defaultStudyMedi\
a' in 'field list' at /Users/dejongh/Desktop/ModelSEED/Model-SEED-core/lib/PPO/PPOBackend.pm line 2\
29.
Successfully imported iYusMp into Model SEED as iYusMp.149!

**Comment by devoid** [comment]
Matt, I think this fixes the first issue. For the defaultStudyMedia, I'm guessing a database update will deal with that. So I'm closing this issue. Reopen it if you are still getting errors.

**Comment by mdejongh** [comment]
How do I do a "database update"?

On Mon, Oct 31, 2011 at 7:37 PM, Scott Devoid
reply@reply.github.com
wrote:

> Matt, I think this fixes the first issue. For the defaultStudyMedia, I'm guessing a database update will deal with that. So I'm closing this issue. Reopen it if you are still getting errors.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ModelSEED/Model-SEED-core/issues/45#issuecomment-2584949

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by devoid** [comment]
Good question... if you haven't made any data changes that you want to save:
drop your existing database:
rm data/ModelDB/ModelDB.db
or
mysql < "DROP DATABASE ModelDB"

download:
http://bioseed.mcs.anl.gov/~devoid/FIG/ModelDB-sqlite.tgz
or
http://bioseed.mcs.anl.gov/~devoid/FIG/ModelDB-mysql.tgz

extract:
tar -xzf ModelDB-suffix.tgz -C path/to/data/
and load into database:
sqlite3 data/ModelDB/ModelDB.db < ModelDB/ModelDB.sqlite

mysql < ModelDB/ModelDB.mysql

If you have changes that you've made, we need to wait until we get APIs to
talk back to the "master-core" in the bio systems.

~ Scott

**Comment by mdejongh** [comment]
The download links you gave me are broken.
