### ISSUE TITLE
Database error and warning when running fbafva and testmodelgrowth

### ISSUE THREAD

**Issue by mdejongh** [ModelSEED/Model-SEED-core#46]
I get these two errors/warnings consistenty when using fbafva and testmodelgrowth:

~/Desktop/ModelSEED/Model-SEED-core> bin/fbafva -model "iYusMp.149"

Processing argument: fbafva
 [PPOBackend.pm 246]Database error: DBD::mysql::st execute failed: Unknown column 'defaultStudyMedi\
a' in 'field list' at /Users/dejongh/Desktop/ModelSEED/Model-SEED-core/lib/PPO/PPOBackend.pm line 2\
29.
mkdir: /Users/dejongh/Desktop/ModelSEED/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/20982\
67/MFAOutput: File exists

**Comment by cshenry** [comment]
Matt, does the model table in your database have a column called "defaultStudyMedia"?
I believe your database scheme does not match the scheme expected by your code. 

One thing we haven't quite figured out yet is how we go about updating the distributed model SEEDs to scheme adjustments. I believe this will come down to exporting your user objects, swapping the db, then importing your user objects again.

**Comment by devoid** [comment]
Closing this issue. Reopen if the `defaultStudyMedia` column error is appearing again.
