### ISSUE TITLE
locating the files I upload to the database

### ISSUE THREAD

**Issue by tammyk** [ModelSEED/Model-SEED-core#48]
I was wondering whether there's a way to see where the files I load to the database from MSModelFiles go? I wanted to keep track of the model/biomass files I personally have loaded and to delete the files I no longer want there (I've been uploading a lot of random files where I was just trying out stuff).

**Comment by cshenry** [comment]
These go into the database. For now, you'll want to find a viewer for sqllite or mysql databases, depending on what you're using. Eventually, we could write a function that enables you to print and delete all the biomass reactions and models you own.

**Comment by samseaver** [comment]
No longer an issue
