### ISSUE TITLE
CHI fails on when caching undef value

### ISSUE THREAD

**Issue by devoid** [ModelSEED/Model-SEED-core#49]
@samseaver
I was trying to run the gap-filling on the latest update, but it had this error:

> ModelDriver encountered an unrecoverable error:

Can't call method "serialize" on an undefined value at
/vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/CHI/CacheObject.pm
line 57

I'm hoping this is easy to fix :-)

BTW, I got File::NSFLock and CHI::?? to install...

**Comment by devoid** [comment]
@samseaver

We missed getting to this the other day, any chance you were able to replicate this bug? I'm guessing not since we have caching disabled completely now.

**Comment by samseaver** [comment]
Can you give me a commit number to pull, for when the caching was enabled?

**Comment by devoid** [comment]
I can't find a good one. Since caching is disabled, I'm going to close this until we get some form of caching working again.
