### ISSUE TITLE
Add command to add users to local install

### ISSUE THREAD

**Issue by cshenry** [ModelSEED/Model-SEED-core#5]
You'll probably want to add a function in configureModelSeed.pl that handles this given the parameters in Settings.txt

```
mysql> insert into users (firstname,lastname,email,login,password)
values ('Sam','Seaver','samseaver@gmail.com','seaver','bollocks')
```

After that, it actually seemed to be running now!  The output had some extra 'test1' statements, left over from debugging I presume:

Processing argument:
importmodel?KEGGimport?83333.1?seaver?/Users/seaver/Documents/Projects/Model_Import_Files/?1
Use of uninitialized value in pattern match (m//) at /Users/seaver/Software/Model-SEED-core/lib/PPO/DBObject.pm line 493.
test1   /Users/seaver/Software/Model-SEED-core/models/seaver/KEGGimport.2/0/biochemistry/reaction.txt
test1   /Users/seaver/Software/Model-SEED-core/models/seaver/KEGGimport.2/0/biochemistry/compound.txt
test1   /Users/seaver/Software/Model-SEED-core/models/seaver/KEGGimport.2/0/biochemistry/cpdals.txt
test1   /Users/seaver/Software/Model-SEED-core/models/seaver/KEGGimport.2/0/biochemistry/rxnals.txt
Found:cpd17154
etc. etc.

**Comment by devoid** [comment]
Ok so it exists but I done understand how to call it...

```
$ ./bin/adduser devoid xxxxx scott devoid devoid\@ci.uchicago.edu
$ ./bin/adduser devoid?xxxxx?scott?devoid?devoid\@ci.uchicago.edu
```

**Comment by cshenry** [comment]
This has now been changed to:
./bin/createlocaluser -login "my username" -password "my password" -firstname "my firstname" -lastname "my lastname" -email "my email"
If the username is found in the SEED, the system will attempt to import all other data from the SEED. So if you're trying to import a SEED account, you only need to provide a login and password.
