### ISSUE TITLE
FBAMODEL.t consumes 4G memory, runs forever

### ISSUE THREAD

**Issue by devoid** [ModelSEED/Model-SEED-core#50]
FBAMODEL.t is currently consuming ~4G of memory and has been running for 5 minutes. We need to try to get this down to an acceptable level. (< 1 minute for all tests)

**Comment by cshenry** [comment]
This is fixed, although I'm not convinced we'll really be able to get all the tests to be that short. If possible, I was thinking this test may just be run automatically on a nightly basis. Perhaps we even go through the entire installation process on several VM on a nightly basis... maybe find a mac machine somewhere and set it up to do this... perhaps the bacillus machine at UC?
