### ISSUE TITLE
ModelDB-sqlite.tgz missing from http://bioseed.mcs.anl.gov/~devoid/

### ISSUE THREAD

**Issue by cshenry** [ModelSEED/Model-SEED-core#52]
Thanks for the heads up. I ran into a little hiccup during the installation. When trying to load the sqlite version of the ModelDB, the installation does the following:

echo "Downloading biochemistry database to $INSTALL_DIE/data/ModelDB/";

curl http://bioseed.mcs.anl.gov/~devoid/ModelDB-sqlite.tgz > $TMPFILE;

tar -xzf $TMPFILE -C $DATA_DIR;

The problem is that the ModelDB-sqlite.tgz does not exist on in the devoid directory. I dug around a bit and found an sqlite version of the ModelDB in the TestDB.tgz file. Is that a working sqlite version of the DB? Would recommend that I work with the sqlite version or quit faffing about and use the MySQL version?
Regards,
James

**Comment by raphyz** [comment]
I did not understand the answer to that :)

Thanks

Raphy

**Comment by devoid** [comment]
Sorry, it was a naming issue. ModelDB.tgz was there (which was the sqlite version). Now that we have a mysql flavor as well, I've created a symlink named `ModelDB-sqlite.tgz` that should be correct. `TestDB.tgz` also contains a sqlite database, but it's got more stuff for doing unit tests.

I don't have James's email, so someone needs to get back to him.
