### ISSUE TITLE
problem when running /Model-SEED-core/bin/ms-config load on a mysql config

### ISSUE THREAD

**Issue by raphyz** [ModelSEED/Model-SEED-core#53]
./Model-SEED-core/bin/ms-config load Model-SEED-core/config/Settings.config.mysql 
g++ -O3 -fPIC -fexceptions -DNDEBUG -DIL_STD -DILOSTRICTPOD -DLINUX -I../Include/ -DNOSAFEMEM -DNOBLOCKMEM -I/home/raphyz/Desktop/SHARE/phd/ModelSEED/glpk/include -I/home/raphyz/phd/cplex1101_64bit/include/ilcplex -o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Linux/mfatoolkit /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/driver.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/MFAProblem.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/CPLEXapi.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/SCIPapi.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/GLPKapi.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/LINDOapiEMPTY.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/SolverInterface.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/Species.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/Data.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/InterfaceFunctions.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/Identity.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/Reaction.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/GlobalFunctions.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/AtomCPP.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/UtilityFunctions.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/AtomType.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/Gene.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/GeneInterval.o /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/software/mfatoolkit/Source/stringDB.o -L/home/raphyz/Desktop/SHARE/phd/ModelSEED/glpk/lib -lglpk -L/home/raphyz/Desktop/SHARE/phd/cplex1101_64bit/bin/x86-64_rhel4.0_3.4 -lcplex -lm -lpthread -lz
Missing right curly or square bracket at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELreaction.pm line 1403, at end of line
syntax error at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELreaction.pm line 1403, at EOF
Compilation failed in require at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 34.
BEGIN failed--compilation aborted at /home/raphyz/Desktop/SHARE/phd/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 34.
Compilation failed in require at /home/raphyz/phd/Model-SEED-core/bin/../lib/ModelSEED/ModelSEEDScripts/ms-config.pl line 342.

**Comment by jamesclulow** [comment]
I'm getting the same error in the FIGMODEL.pm when running the config.
Missing right curly or square bracket at /Users/james/Desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELreaction.pm line 1403, at end of line
syntax error at /Users/james/Desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELreaction.pm line 1403, at EOF
Compilation failed in require at /Users/james/Desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 34.
BEGIN failed--compilation aborted at /Users/james/Desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 34.Compilation failed in require at /Users/james/Desktop/Model-SEED-core/bin/../lib/ModelSEED/ModelSEEDScripts/ms-config.pl line 342.

Any solutions found for you raphyz?

**Comment by samseaver** [comment]
I fixed this particular issue in FIGMODELreaction.pm
