### ISSUE TITLE
Misnamed compound id in database download

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#54]
In compound_alias, this record:

`'1316302', 'KEGG', 'C00301', 'cdp00251'

is incorrect, the 'd' and the 'p' need to be transposed as in 'cpd' instead of 'cdp'.  This needs to be corrected in the original database download.

**Comment by devoid** [comment]
I've made this change in the master-core database. Local core databases need to be updated manually.

**Comment by samseaver** [comment]
Another one:

'gly-tyr-L','gly-tyr-L','iYO844'

The closest match is this:
'cpd15606','glytyr','searchname'

so these two lines should be added:

'cpd15606','gly-tyr-L','iYO844'
'cpd15606','glytyrl','searchname'

**Comment by samseaver** [comment]
I went ahead and did this myself in the production database, but again, the changes needed to be done to the database dumps for ModelSEEDCore
