### ISSUE TITLE
Configuration problems on biologin-4

### ISSUE THREAD

**Issue by mdejongh** [ModelSEED/Model-SEED-core#55]
I'm trying to configure the Model-SEED-Core on my personal account on biologin-4; I have the following entries in my BioSettings.config:

[Optimizers]
includeDirectoryCPLEX=/vol/model-prod/Software/solvers/cplex/include/ilcplex/
libraryDirectoryCPLEX=/vol/model-prod/Software/solvers/cplex/lib/x86-64_sles10_4.1/static_pic/
licenceDirectoryCPLEX=/vol/model-prod/Software/solvers/cplex/access.ilm
# includeDirectoryGLPK=
# libraryDirectoryGLPK=

Even though the GLPK entries are commented out, I get the following errors when doing a ms-config load:

home/dejongh/Model-SEED-core/software/mfatoolkit/Source/GLPKapi.o: In function `GLPKClearSolver()':
GLPKapi.cpp:(.text+0x91): undefined reference to`_glp_lpx_delete_prob'
/home/dejongh/Model-SEED-core/software/mfatoolkit/Source/GLPKapi.o: In function `GLPKInitialize()':
GLPKapi.cpp:(.text+0xbf): undefined reference to`_glp_lpx_create_prob'
GLPKapi.cpp:(.text+0xcf): undefined reference to `_glp_lpx_set_class'

etc...

**Comment by devoid** [comment]
I think GLPK is required for the compilation to proceed smoothly. Here are
the appropriate links:

includeDirectoryGLPK=/vol/model-prod/Software/solvers/glpk-4.38/include/
libraryDirectoryGLPK=/vol/model-prod/Software/solvers/glpk-4.38/src/.libs/

As for wether we _need_ GLPK in the case where a user has CPLEX, I'll have
to defer to Chris on that one.
~ Scott

**Comment by cshenry** [comment]
You do need GLPK. At this time, you always need glpk. Not sure why those include and library lines were empty...
