### ISSUE TITLE
Error during installation on Rob Edward's machine

### ISSUE THREAD

**Issue by cshenry** [ModelSEED/Model-SEED-core#56]
The error appears to be a commented out } at the end of processReactionWithMFAToolkit

If I correct that, the error I now get is ""Unable to find database configuration for ModelDB USERS"" at /data/ModelSeed/lib/ModelSEED/FIGMODEL.pm line 134

Rob

**Comment by linsalrob** [comment]
Fresh pull tonight, running ms-config load Mysettings:

Use of uninitialized value in concatenation (.) or string at /data/ModelSeed/bin/../lib/ModelSEED/ModelSEEDScripts/ms-config.pl line 117.
Use of uninitialized value in concatenation (.) or string at /data/ModelSeed/bin/../lib/ModelSEED/ModelSEEDScripts/ms-config.pl line 151.
[: 4: unexpected operator
g++ -O3 -fPIC -fexceptions -DNDEBUG -DIL_STD -DILOSTRICTPOD -DLINUX -I../Include/ -DNOSAFEMEM -DNOBLOCKMEM -I/usr/include -o /data/ModelSeed/software/mfatoolkit/Linux/mfatoolkit /data/ModelSeed/software/mfatoolkit/Source/driver.o /data/ModelSeed/software/mfatoolkit/Source/MFAProblem.o /data/ModelSeed/software/mfatoolkit/Source/CPLEXapiEMPTY.o /data/ModelSeed/software/mfatoolkit/Source/SCIPapi.o /data/ModelSeed/software/mfatoolkit/Source/GLPKapi.o /data/ModelSeed/software/mfatoolkit/Source/LINDOapiEMPTY.o /data/ModelSeed/software/mfatoolkit/Source/SolverInterface.o /data/ModelSeed/software/mfatoolkit/Source/Species.o /data/ModelSeed/software/mfatoolkit/Source/Data.o /data/ModelSeed/software/mfatoolkit/Source/InterfaceFunctions.o /data/ModelSeed/software/mfatoolkit/Source/Identity.o /data/ModelSeed/software/mfatoolkit/Source/Reaction.o /data/ModelSeed/software/mfatoolkit/Source/GlobalFunctions.o /data/ModelSeed/software/mfatoolkit/Source/AtomCPP.o /data/ModelSeed/software/mfatoolkit/Source/UtilityFunctions.o /data/ModelSeed/software/mfatoolkit/Source/AtomType.o /data/ModelSeed/software/mfatoolkit/Source/Gene.o /data/ModelSeed/software/mfatoolkit/Source/GeneInterval.o /data/ModelSeed/software/mfatoolkit/Source/stringDB.o -L/usr/lib -lglpk
""Unable to find database configuration for ModelDB USERS"" at /data/ModelSeed/lib/ModelSEED/FIGMODEL.pm line 136
        ModelSEED::FIGMODEL::FIGMODELERROR('Unable to find database configuration for ModelDB USERS') called at /data/ModelSeed/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 158
        ModelSEED::FIGMODEL::FIGMODELdatabase::get_object_manager('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x30888d8)', 'user') called at /data/ModelSeed/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 272
        ModelSEED::FIGMODEL::FIGMODELdatabase::sudo_get_objects('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x30888d8)', 'user', 'HASH(0x3088c80)') called at /data/ModelSeed/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 298
        ModelSEED::FIGMODEL::FIGMODELdatabase::get_objects('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x30888d8)', 'user', 'HASH(0x3088c80)') called at /data/ModelSeed/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 249
        ModelSEED::FIGMODEL::FIGMODELdatabase::get_object('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x30888d8)', 'user', 'HASH(0x3088c80)') called at /data/ModelSeed/bin/../lib/ModelSEED/ModelSEEDScripts/ms-config.pl line 376

**Comment by devoid** [comment]
Can you attach your Mysettings.conf file? Removing any username/password pairs if they are present. I'm thinking you have something like:

```
[Optional]
dataDirectory=
```

When you want to either define it or comment it out.

**Comment by devoid** [comment]
I'm closing this issue since it appears to be a configuration problem. @linsalrob Are you Rob Edwards? If you are still experiencing problems, check the last comment regarding the dataDirectory option. If that doesn't fix it for you, feel free to reopen the issue, posting most of the configuration here.
