### ISSUE TITLE
Error importing user model from SEED

### ISSUE THREAD

**Issue by jamesclulow** [ModelSEED/Model-SEED-core#57]
I created a model using the RAST annotation server and am trying to import it onto my local computer. I notice some strange things. If I use the model name found via the web client of the Model seed in the following command

./bin/mdlimportmodel -name "Seed392499.22.46352" -genome "392499.22"

It imports as Seed392499.22.46352.46352.46352 (I'm guessing that the 46352 is a tag for my user ID? as I see it added to other models I have imported.)

What is the correct model name to be using?

Also I find the following error when trying to import the model:

> ModelDriver encountered an unrecoverable error:

500 Error detected by service. at /Users/james/desktop/Model-SEED-core/lib/myRAST/ClientThing.pm line 724
    ClientThing::_send_request('MSSeedSupportClient=HASH(0x10510edb0)', 'function', 'getRastGenomeData', 'args', '---\x{a}genome: 392499.22\x{a}password: SbsmC6BNxSwos\x{a}username: james...', 'source', 'ClientThing', 'dbName', undef, ...) called at /Users/james/desktop/Model-SEED-core/lib/myRAST/ClientThing.pm line 476
    ClientThing::_call_method('MSSeedSupportClient=HASH(0x10510edb0)', 'getRastGenomeData', 'HASH(0x102dddce8)') called at /Users/james/desktop/Model-SEED-core/lib/myRAST/ClientThing.pm line 248
    ClientThing::AUTOLOAD('MSSeedSupportClient=HASH(0x10510edb0)', 'HASH(0x102dddce8)') called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELgenome.pm line 301
    ModelSEED::FIGMODEL::FIGMODELgenome::getRastGenomeData('ModelSEED::FIGMODEL::FIGMODELgenome=HASH(0x10a4ffcd8)') called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELgenome.pm line 370
    ModelSEED::FIGMODEL::FIGMODELgenome::update_genome_stats('ModelSEED::FIGMODEL::FIGMODELgenome=HASH(0x10a4ffcd8)') called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELgenome.pm line 33
    ModelSEED::FIGMODEL::FIGMODELgenome::new('ModelSEED::FIGMODEL::FIGMODELgenome', 'ModelSEED::FIGMODEL=HASH(0x100834480)', 392499.22) called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 1073
    ModelSEED::FIGMODEL::get_genome('ModelSEED::FIGMODEL=HASH(0x100834480)', 392499.22) called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELmodel.pm line 491
    ModelSEED::FIGMODEL::FIGMODELmodel::genomeObj('ModelSEED::FIGMODEL::FIGMODELmodel=HASH(0x102a79e88)') called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELmodel.pm line 3752
    ModelSEED::FIGMODEL::FIGMODELmodel::GenerateModelProvenance('ModelSEED::FIGMODEL::FIGMODELmodel=HASH(0x102a79e88)', 'HASH(0x102a7d738)') called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELmodel.pm line 252
    ModelSEED::FIGMODEL::FIGMODELmodel::initializeModel('ModelSEED::FIGMODEL::FIGMODELmodel=HASH(0x102a79e88)', 'HASH(0x102a6fe10)') called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELmodel.pm line 36
    ModelSEED::FIGMODEL::FIGMODELmodel::new('ModelSEED::FIGMODEL::FIGMODELmodel', 'HASH(0x102a70410)') called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 3662
    ModelSEED::FIGMODEL::create_model('ModelSEED::FIGMODEL=HASH(0x100834480)', 'HASH(0x102a6fe10)') called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 2719
    ModelSEED::FIGMODEL::import_model('ModelSEED::FIGMODEL=HASH(0x100834480)', 'HASH(0x102a6ff78)') called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pm line 6013
    ModelSEED::ModelDriver::mdlimportmodel('ModelSEED::ModelDriver=HASH(0x1008348d0)', 'mdlimportmodel', 'HASH(0x1029e5ef0)') called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 87
    main::__ANON__() called at /usr/local/ActivePerl-5.14/lib/Try/Tiny.pm line 76
    eval {...} called at /usr/local/ActivePerl-5.14/lib/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x1029e6640)', 'Try::Tiny::Catch=REF(0x100834390)') called at /Users/james/desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 91
    require /Users/james/desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pl called at /Users/james/desktop/Model-SEED-core/config//ModelSEEDbootstrap.pm line 19
    main::run() called at -e line 3

It appears to me to be having issues with the genome data? Perhaps this ties in with the suggestion to be able to import a model without a tie to the genome ID?

**Comment by samseaver** [comment]
About the genome:

Sphingomonas wittichii RW1 only has the genome id: 392499.4

available in RAST, as seen here:
http://rast.nmpdr.org/seedviewer.cgi

Whilst PubSEED shows these two available ids:  392499.4, and  392499.14

Whilst 392499.22 may exist somewhere, it may not be reachable by the clients used in ModelSEEDCore.  However, a search of PubSEED using the species name gave me the alternate ids that you could use.

We probably should handle the ClientThing error better.

**Comment by cshenry** [comment]
So I adjusted the import code. You should provide the exact ID of the model you want to import. The system now assumes the import file is in your workspace directory with this filename: "Model-SEED-core/workspace/(your username)/(your current workspace)/(model ID).mdl". Note, when you run "mdlprintmodel", this is the file that gets generated. The import file should have an "mdl" extension. If your imported model ID has no suffix based on your user ID, the system will add this extension to the ID. However, it will no longer always add this extension, so you no longer will have model names like Seed....46352.46352. Hopefully this will reduce confusion when using this function, and hopefully this resolves the issue.
