### ISSUE TITLE
Indexing of fields in compound_alias

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#59]
I got a new problem which I wasn't getting before.

If my code tries to insert these two set of records:

'cpd00306','D-xylitol','nameTestModel.45632'
'cpd00306','D-Xylitol','nameTestModel.45632'

It will fail.  This is a new error for me, and I'm not sure what I wasn't getting it before.  I take it that the indexes for the compound_alias table disregard the case of the letters in the alias field.

I would like to insert a try/catch statement for these attempted duplicates, so that the code doesn't crash on me, is there an established code for this when trying to insert into the database?

**Comment by devoid** [comment]
There is no database specific code for catching errors; however you may try
the "Try::Tiny" package which would have the syntax:

try {
    errorProne();
} catch {
    handleErrors();
} finally {
    alwaysDo();
};  # < that semicolon is important!

Although I've had problems with the catch block being ignored, so you might
just do:
eval {
    errorProne();
};
if($@) {
    handleErrors();
}

Just don't mess with $@ as it's a global object.
~ Scott

**Comment by devoid** [comment]
Closing this as there doesn't seem to be an error (insert attempts that violate index uniqueness rules will always fail).
