### ISSUE TITLE
fbafva operation does not work properly

### ISSUE THREAD

**Issue by pvilaca** [ModelSEED/Model-SEED-core#60]
When I run:

_./bin/fbafva -model iJR904.1_

I get:

_Processing argument: fbafva
Creating the model file: /home/pvilaca/modelseed/install/data/ReactionDB/MFAToolkitOutputFiles/31/iJR904.1.tbl
Creating biochemistry provenance files
mkdir: cannot create directory `/home/pvilaca/modelseed/install/data/ReactionDB/MFAToolkitOutputFiles/31/MFAOutput': File exists
Filename required by Spreadsheet::WriteExcel->new() at /home/pvilaca/modelseed/install/lib/ModelSEED/FIGMODEL/FIGMODELTable.pm line 1140
Whoops! We encountered an unrecoverable error._

I opened the file ./lib/ModelSEED/FIGMODEL/FIGMODELTable.pm and I noticed that the variable $workbook in line 1140 was empty...

**Comment by cshenry** [comment]
I believe this is fixed now.
