### ISSUE TITLE
Run Model SEED config

### ISSUE THREAD

**Issue by alikpel** [ModelSEED/Model-SEED-core#61]
Hi

When I run:

./Model-SEED-core/bin/ms-config load Model-SEED-core/config/MySettings.config

I get:

g++ -O3 -fPIC -fexceptions -DNDEBUG -DIL_STD -DILOSTRICTPOD -DLINUX -I -I/usr/lib -I../Include -DNOSAFEMEM -DNOBLOCKMEM -o mfatoolkit ../Source/driver.o ../Source/MFAProblem.o ../Source/CPLEXapiEMPTY.o ../Source/SCIPapi.o ../Source/GLPKapi.o ../Source/LINDOapiEMPTY.o ../Source/SolverInterface.o ../Source/Species.o ../Source/Data.o ../Source/InterfaceFunctions.o ../Source/Identity.o ../Source/Reaction.o ../Source/GlobalFunctions.o ../Source/AtomCPP.o ../Source/UtilityFunctions.o ../Source/AtomType.o ../Source/Gene.o ../Source/GeneInterval.o ../Source/stringDB.o -L/usr/include -lglpk

what does it mean?

Alik

**Comment by alikpel** [comment]
MY config file look like this:

[Database]

# type is either sqlite or mysql

type=sqlite

# required for sqlite

filename=/specific/disk1/home/alexnade/Model-SEED-core/data/ModelDB/ModelDB.db

# required for mysql

# username=seed

# password=seedxhs

# host=localhost

# socket=/var/run/mysqld/mysqld.sock

# port=3306

[Optional]
dataDirectory=/specific/disk1/home/alexnade/Model-SEED-core/data/

# admin_users=admin1,admin2

[Optimizers]
includeDirectoryGLPK=/usr/lib/
libraryDirectoryGLPK=/usr/include/
#includeDirectoryCPLEX=/usr/local/lib/cplex121/include/
#libraryDirectoryCPLEX=/usr/local/lib/cplex121/lib/x86-64_sles9.0_3.3/static_pic/
#licenceDirectoryCPLEX=/usr/ilog/ilm/

**Comment by devoid** [comment]
By default when you run ms-config, it also compiles the MFAToolkit (g++ is a
C++ compiler). That message is just the last step that the compiler performs
to build the toolkit; it's normal and means things are working properly.
Although, I can see how it would be confusing and we should probably return
a more useful message.

~ Scott

**Comment by cshenry** [comment]
Added a success message to ms-config.
