### ISSUE TITLE
mslogin message

### ISSUE THREAD

**Issue by levinas** [ModelSEED/Model-SEED-core#62]
When I ran mslogin, I got the following message. I think authentication was successful and it's true that no user account is named "reviewer", but still is the second line of the output a little confusing?

> mslogin -username reviewer -password reviewer                 [ /lustre/beagle/fangfang/ModelSEED/temp ]

Processing argument: mslogin
No user account found with name: reviewer!
Authentication Successful!
You will remain logged in as "reviewer" until you run the "login" or "logout" functions.
You have switched from workspace "PUBLIC:default" to workspace "reviewer:default"!

**Comment by cshenry** [comment]
A good point. I adjusted the code to throw an exception when it encounters this error. My suspicion is a lack of connectivity preventing the system from importing the user account from the SEED. But I'll close this issue since I've resolved the problem of the confusing message.
