### ISSUE TITLE
logging into a Model SEED

### ISSUE THREAD

**Issue by alikpel** [ModelSEED/Model-SEED-core#64]
Hi,

When I run  

./bin/login -username alik  -password ***

I get: 

Processing argument: login
Input password does not match user account!
Authentication Successful! You will now remain logged in as "alik" until you run the "login" or "logout" functions.

There is no problem to enter with the same username and pass into viewer.theseed.org

Alik

**Comment by cshenry** [comment]
I responded to this issue in another thread. I'm going to close this thread.
