### ISSUE TITLE
ModelDriver parsesbml error

### ISSUE THREAD

**Issue by EliKrumholz** [ModelSEED/Model-SEED-core#65]
When I try to parse an sbml model I am returned the following error:

$./ModelDriver parsesbml -file /path/to/file.xml

Can't locate object method "parseSBMLtoTabTable" via package "ModelSEED::FIGMODEL" at /Users/elikrumholz/gitProjects/Model-SEED-Core-10_4_11/lib/ModelSEED/ModelDriver.pm line 4652.

Is this function still the standard way to import an sbml model, or is there another import function that supports sbml models?

**Comment by samseaver** [comment]
I'd made big changes to this function, including its name, and so in the latest commit, you should find it working now.  The method you used to call the function is the same, and it should print the tables to:

/path/to/file-*.tbl

where *.tbl is compartments, compounds, and reactions.

file-compartments.tbl is actually not used by importmodel, but is there for useful reference.

Everything in the original xml should be found in these tables, so I will close this issue, but you can either re-open it, or open a new one, if you feel there are still problems.

**Comment by samseaver** [comment]
As an update, the file function got renamed to mdlparsesbml
