### ISSUE TITLE
logging into a Model SEED

### ISSUE THREAD

**Issue by alikpel** [ModelSEED/Model-SEED-core#66]
Hi,

I have re-installed  SEED

but now  when i run 
./bin/login -username "my SEED username" -password "my SEED password"
i get
./bin/login: Command not found.

I checked the file is actually missing  (logout file also missing)
i tried to re-install but the file is still missing.

when i try instead to run 
.beast 15% ./mslogin -username **\* -password ***
i see no response:
beast 16% 

Alik

**Comment by jamesclulow** [comment]
mslogin works for me on MacOS X 10.7. Perhaps an internet connectivity problem?

**Comment by cshenry** [comment]
Regarding the missing files, many functions were renamed recently to provide them with a "namespace". Given the large numbers of binaries we ultimately expect to have in the "bin" directory, we thought this would be useful. Workspace functions all start with "ms". Biochemistry functions start with "bc". Model functions start with "mdl". And fba functions start with "fba". Given all these changes, our documentation became badly out of date. I recently developed code that automatically creates the documentation from the code itself, called "ms-create-wiki-docs". We should see the documentation remain much more up to date now.

Regarding the lack of response when you ran "mslogin", my guess is you actually have a dependency issue or something like that, but the errors aren't showing up. I believe I have corrected this. Please do a git update and rerun ms-config load.

**Comment by alikpel** [comment]
Hi,

I re-installed Model SEED  and know when I try to log in i get :

"
beast 14% ./ms-login -username **\* -password ***
Whoops! We encountered an unrecoverable error.

No user account found with name: alik!

A complete log of the problem has been printed to:

/specific/disk1/home/alexnade/Model-SEED-core/.errors/error-eYIeA

Have you updated recently? ( git pull )
Have you changed your configuration? ( ms-config )

If you are still having problems, please submit a ticket
copying the contents of the error file printed above to:

https://github.com/ModelSEED/Model-SEED-core/issues/new

and in error-Pjdpw  file:

"
error-Pj

> ModelDriver encountered an unrecoverable error:

""No user account found with name: alik!"" at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 136
    ModelSEED::FIGMODEL::FIGMODELERROR('No user account found with name: alik!') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 954
    ModelSEED::FIGMODEL::authenticate('ModelSEED::FIGMODEL=HASH(0x3be8dd8)', 'HASH(0x3be5bb8)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 520
    ModelSEED::FIGMODEL::process_arguments('ModelSEED::FIGMODEL=HASH(0x3be8dd8)', 'HASH(0x3be5bb8)', 'ARRAY(0x3c8fcb0)', 'HASH(0x3be5d38)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 977
    ModelSEED::FIGMODEL::import_seed_account('ModelSEED::FIGMODEL=HASH(0x3be8dd8)', 'HASH(0x3be5bb8)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pm line 5379
    ModelSEED::ModelDriver::mslogin('ModelSEED::ModelDriver=HASH(0x3be92b8)', 'mslogin', 'HASH(0x3bd8f68)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 86
    main::**ANON**() called at /usr/share/perl5/Try/Tiny.pm line 76
    eval {...} called at /usr/share/perl5/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x3bcfdf0)', 'Try::Tiny::Catch=REF(0x3be8ce8)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 90
    require /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pl called at /specific/disk1/home/alexnade/Model-SEED-core/config//ModelSEEDbootstrap.pm line 20
main::run() called at -e line 3

and again ,there is no problem to enter with the same username and pass into viewer.theseed.org

Thanks,
Alik

**Comment by devoid** [comment]
Can you run the following command while in the ~/Model-SEED-core/ directory:

```
git pull origin master
```

That will do a code update. Based on your error message, it looks like you
are still running under an older version of the code (the latest version
prints the version number in the error message).

~ Scott

**Comment by alikpel** [comment]
Hi,

Just re-installed it once again. and it worked.  

tnx
Alik

**Comment by alikpel** [comment]
Hi 

I updated to a newer version and once again i get an error while trying to log in

> ModelDriver encountered an unrecoverable error:

```
""No user account found with name: alik!"" at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/globals.pm line 91
    ModelSEED::globals::ERROR('No user account found with name: alik!') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 906
    ModelSEED::FIGMODEL::authenticate('ModelSEED::FIGMODEL=HASH(0x3c32018)', 'HASH(0x3c2ded8)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 502
    ModelSEED::FIGMODEL::process_arguments('ModelSEED::FIGMODEL=HASH(0x3c32018)', 'HASH(0x3c2ded8)', 'ARRAY(0x3e02f90)', 'HASH(0x3c2dff8)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 929
    ModelSEED::FIGMODEL::import_seed_account('ModelSEED::FIGMODEL=HASH(0x3c32018)', 'HASH(0x3c2ded8)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pm line 5270
    ModelSEED::ModelDriver::mslogin('ModelSEED::ModelDriver=HASH(0x3c32480)', 'mslogin', 'HASH(0x3c1ea38)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 90
    main::__ANON__() called at /usr/share/perl5/Try/Tiny.pm line 76
    eval {...} called at /usr/share/perl5/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x3c15090)', 'Try::Tiny::Catch=REF(0x3c31f28)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 94
    require /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pl called at /specific/disk1/home/alexnade/Model-SEED-core/config//ModelSEEDbootstrap.pm line 21
    main::run() called at -e line 3
```

> Model-SEED-core revision: e86350abab5006936b727e5d8160923d388edd02

tnx
Alik
