### ISSUE TITLE
Error Making MFAToolkit...

### ISSUE THREAD

**Issue by jamesclulow** [ModelSEED/Model-SEED-core#68]
I just did a git pull to update and then tried to reconfigure and get the following errors on MacOS X 10.7 when trying to make mfatoolkit.
g++ -O3 -fPIC -fexceptions -DNDEBUG -DIL_STD -DILOSTRICTPOD -DLINUX -I../Include/ -DNOSAFEMEM -DNOBLOCKMEM -I/usr/local/Cellar/glpk/4.47/include -I/Users/jamesclulow/Applications/IBM/ILOG/CPLEX_Studio123/cplex/include/ilcplex -c /Users/jamesclulow/desktop/Model-SEED-core/software/mfatoolkit/Source/UtilityFunctions.cpp; mv _.o /Users/jamesclulow/desktop/Model-SEED-core/software/mfatoolkit/Source
/Users/jamesclulow/desktop/Model-SEED-core/software/mfatoolkit/Source/UtilityFunctions.cpp:22:16: error: io.h: No such file or directory
mv: rename *.o to /Users/jamesclulow/desktop/Model-SEED-core/software/mfatoolkit/Source/_.o: No such file or directory
make: **\* [/Users/jamesclulow/desktop/Model-SEED-core/software/mfatoolkit/Source/UtilityFunctions.o] Error 1

Any suggestions?

**Comment by jamesclulow** [comment]
Nevermind, found a version of io.h in the MacOS X 10.7 sdk and copied it into the include directory. Make worked fine. (Might be a good idea to include it in the directory for those on Mac?)

**Comment by mdejongh** [comment]
Hi James,

Where did you find io.h?  I'm having the same problem.  Thanks, Matt

**Comment by jamesclulow** [comment]
Just search io.h in spotlight and open the one from MacOSX10.7.sdk. Once opened in Xcode, Save as onto your Desktop and move into the Include directory of mfatoolkit.

**Comment by samseaver** [comment]
10.7 is Lion.  Do you have Developer Tools installed?  

I've not used Lion, but I've got DT installed on my Snow Leopard, did you two have the option of installing things like XCode, Unix Development Support etc?

It seems that Lion bundles it all with XCode now:

http://hints.macworld.com/article.php?story=20110721055416487
http://developer.apple.com/technologies/tools/

**Comment by jamesclulow** [comment]
Yeah Sam. Have Xcode installed prom the package that came with Lion. It seems for some reason that the io.h doesn't go into the normal libs but it exists on the computer in the SDK packages? I found it and just moved a copy to the local directory where it was needed. Worked fine.

**Comment by samseaver** [comment]
Well, whaddya know?! I just got the same error on biologin-4...

but biologin-4 has io.h in /usr/include/sys/io.h

So I figured out the error, and its fixed in the latest update, the include should have read

`#include <sys/io.h>`

If you want to be sure its on your system without copying it anywhere, you can try:

`locate sys/io.h`
