### ISSUE TITLE
Error in ms-config success announcement

### ISSUE THREAD

**Issue by jamesclulow** [ModelSEED/Model-SEED-core#69]
I get the following error popping up after the config is completed. I run the following command:
$ ./Model-SEED-core/bin/ms-config load Model-SEED-core/config/MySettings.config
make: `MFATOOLKIT' is up to date.
Can't call method "e" without a package or object reference at /Users/jamesclulow/Desktop/Model-SEED-core/bin/../lib/ModelSEED/ModelSEEDScripts/ms-config.pl line 406.

I had a look at the code. It seems that it doesn't want to call the success of mfatoolkit installation? It looks to me that it  is checking for the executable mfatoolkit. In my case it is there. So not sure why it is throwing out the error.

**Comment by mdejongh** [comment]
Added a missing dash before the "e" which test for file existence
