### ISSUE TITLE
mslogin error

### ISSUE THREAD

**Issue by jamesclulow** [ModelSEED/Model-SEED-core#70]
I run the following command and find:
./mslogin -username jamesclulow -password *****

Processing argument: mslogin
Whoops! We encountered an unrecoverable error.

No user account found with name: jamesclulow!

A complete log of the problem has been printed to:

/Users/jamesclulow/Desktop/Model-SEED-core/.errors/error-RY7ug

> ModelDriver encountered an unrecoverable error:

""No user account found with name: jamesclulow!"" at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 136
        ModelSEED::FIGMODEL::FIGMODELERROR('No user account found with name: jamesclulow!') called at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 913
        ModelSEED::FIGMODEL::authenticate('ModelSEED::FIGMODEL=HASH(0x7fa22c0320a0)', 'HASH(0x7fa22e1c3dd0)') called at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 520
        ModelSEED::FIGMODEL::process_arguments('ModelSEED::FIGMODEL=HASH(0x7fa22c0320a0)', 'HASH(0x7fa22e1c3dd0)', 'ARRAY(0x7fa22c3815b0)', 'HASH(0x7fa22c0327c0)') called at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 936
        ModelSEED::FIGMODEL::import_seed_account('ModelSEED::FIGMODEL=HASH(0x7fa22c0320a0)', 'HASH(0x7fa22e1c3dd0)') called at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pm line 5379
        ModelSEED::ModelDriver::mslogin('ModelSEED::ModelDriver=HASH(0x7fa22c032508)', 'mslogin', 'HASH(0x7fa22e1ca120)') called at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 86
        main::**ANON**() called at /System/Library/Perl/Extras/5.12/Try/Tiny.pm line 76
@

**Comment by jamesclulow** [comment]
```
    eval {...} called at /System/Library/Perl/Extras/5.12/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x7fa22e1ca870)', 'Try::Tiny::Catch=REF(0x7fa22c031fb0)') called at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 90
    require /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/ModelDriver.pl called at /Users/jamesclulow/Desktop/Model-SEED-core/config//ModelSEEDbootstrap.pm line 21
    main::run() called at -e line 3
```

Sorry didn't include all of the error there.

**Comment by devoid** [comment]
I think this issue is fixed in the most recent update. Please reopen if you are still having problems though.
