### ISSUE TITLE
error simulating single knockouts

### ISSUE THREAD

**Issue by levinas** [ModelSEED/Model-SEED-core#72]
Here's the error message:

fbasingleko -model "iJR904.16242"

ModelDriver encountered an unrecoverable error:

""Could not load results for combination knockout study"" at /lustre/beagle/fangfang/ModelSEED/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 136
        ModelSEED::FIGMODEL::FIGMODELERROR('Could not load results for combination knockout study') called at /lustre/beagle/fangfang/ModelSEED/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELmodel.pm line 7437
        ModelSEED::FIGMODEL::FIGMODELmodel::fbaComboDeletions('ModelSEED::FIGMODEL::FIGMODELmodel=HASH(0x410f838)', 'HASH(0x4134f70)') called at /lustre/beagle/fangfang/ModelSEED/Model-SEED-core/lib/ModelSEED/ModelDriver.pm line 5606
        ModelSEED::ModelDriver::fbasingleko('ModelSEED::ModelDriver=HASH(0x40524a0)', 'fbasingleko', 'HASH(0xd8f430)') called at /lustre/beagle/fangfang/ModelSEED/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 86
        main::**ANON**() called at /home/fangfang/perl5/lib/perl5/Try/Tiny.pm line 76
        eval {...} called at /home/fangfang/perl5/lib/perl5/Try/Tiny.pm line 67
        Try::Tiny::try('CODE(0x404cff8)', 'Try::Tiny::Catch=REF(0x404daa8)') called at /lustre/beagle/fangfang/ModelSEED/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 90
        require /lustre/beagle/fangfang/ModelSEED/Model-SEED-core/lib/ModelSEED/ModelDriver.pl called at /lustre/beagle/fangfang/ModelSEED/Model-SEED-core/config//ModelSEEDbootstrap.pm line 23
        main::run() called at -e line 3

**Comment by devoid** [comment]
Closing due to age.
