### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by linsalrob** [ModelSEED/Model-SEED-core#73]
Still not getting install to work. This is on a relatively clean 64-bit linux with no FIG system available.

redwards@goldeneye:/data/ModelSeed$ git pull
Already up-to-date.
redwards@goldeneye:/data/ModelSeed$ cat config/MySettings.config 

```
[Database]
# type is either sqlite or mysql
type=sqlite

# required for sqlite
filename=/data/ModelSeed/databases/db.sqllite

# required for mysql
# username=
# password=
# host=
# socket=
# port=
```

    
    [Optional]
    # dataDirectory==/data/ModelSeed/data/
    
    [Optimizers]
    # # admin_users=admin1,admin2: this configuration is no longer in use and can be deleted
    includeDirectoryGLPK=/usr/include
    libraryDirectoryGLPK=/usr/lib
    # includeDirectoryCPLEX=
    # libraryDirectoryCPLEX=
    # licenceDirectoryCPLEX=

```
redwards@goldeneye:/data/ModelSeed$ ./bin/ms-config load config/MySettings.config 
```

Your configuration file was adjusted based on changes made to the installation process. Please check the file!

[: 4: unexpected operator
g++ -O3 -fPIC -fexceptions -DNDEBUG -DIL_STD -DILOSTRICTPOD -DLINUX -I../Include/ -DNOSAFEMEM -DNOBLOCKMEM -I/usr/include -o /data/ModelSeed/software/mfatoolkit/Linux/mfatoolkit /data/ModelSeed/software/mfatoolkit/Source/driver.o /data/ModelSeed/software/mfatoolkit/Source/MFAProblem.o /data/ModelSeed/software/mfatoolkit/Source/CPLEXapiEMPTY.o /data/ModelSeed/software/mfatoolkit/Source/SCIPapi.o /data/ModelSeed/software/mfatoolkit/Source/GLPKapi.o /data/ModelSeed/software/mfatoolkit/Source/LINDOapiEMPTY.o /data/ModelSeed/software/mfatoolkit/Source/SolverInterface.o /data/ModelSeed/software/mfatoolkit/Source/Species.o /data/ModelSeed/software/mfatoolkit/Source/Data.o /data/ModelSeed/software/mfatoolkit/Source/InterfaceFunctions.o /data/ModelSeed/software/mfatoolkit/Source/Identity.o /data/ModelSeed/software/mfatoolkit/Source/Reaction.o /data/ModelSeed/software/mfatoolkit/Source/GlobalFunctions.o /data/ModelSeed/software/mfatoolkit/Source/AtomCPP.o /data/ModelSeed/software/mfatoolkit/Source/UtilityFunctions.o /data/ModelSeed/software/mfatoolkit/Source/AtomType.o /data/ModelSeed/software/mfatoolkit/Source/Gene.o /data/ModelSeed/software/mfatoolkit/Source/GeneInterval.o /data/ModelSeed/software/mfatoolkit/Source/stringDB.o -L/usr/lib -lglpk
""Unable to find database configuration for ModelDB USERS"" at /data/ModelSeed/lib/ModelSEED/FIGMODEL.pm line 136
        ModelSEED::FIGMODEL::FIGMODELERROR('Unable to find database configuration for ModelDB USERS') called at /data/ModelSeed/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 158
        ModelSEED::FIGMODEL::FIGMODELdatabase::get_object_manager('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x28c6d28)', 'user') called at /data/ModelSeed/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 272
        ModelSEED::FIGMODEL::FIGMODELdatabase::sudo_get_objects('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x28c6d28)', 'user', 'HASH(0x28c6a10)') called at /data/ModelSeed/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 298
        ModelSEED::FIGMODEL::FIGMODELdatabase::get_objects('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x28c6d28)', 'user', 'HASH(0x28c6a10)') called at /data/ModelSeed/lib/ModelSEED/FIGMODEL/FIGMODELdatabase.pm line 249
        ModelSEED::FIGMODEL::FIGMODELdatabase::get_object('ModelSEED::FIGMODEL::FIGMODELdatabase=HASH(0x28c6d28)', 'user', 'HASH(0x28c6a10)') called at /data/ModelSeed/bin/../lib/ModelSEED/ModelSEEDScripts/ms-config.pl line 392

**Comment by devoid** [comment]
I think your database schema is out of date.

Try downloading a new copy of the database from:
http://bioseed.mcs.anl.gov/~devoid/ModelDB-sqlite.tgz

And extracting it:

```
tar -xzf ModelDB-sqlite.tgz -C /root/data/
```

where `/root/data/` is your data directory

Then loading the sqlite dump into a database:

```
sqlite3 /root/data/ModelDB/ModelDB.db < /root/data/ModelDB/ModelDB.sqlite
```

**Comment by linsalrob** [comment]
Wow, that gave me massive amounts of errors, mainly that alias, type, REACTION are not unique. 

However, that, together with changing the config line:
filename=/data/ModelSeed/databases/db.sqllite
to
filename=/data/ModelSeed/data/ModelDB/ModelDB.db

successfully installed the database. I'm going to consider this closed,

Thanks!!

Rob

**Comment by devoid** [comment]
Oh, sorry. The instructions I gave you neglected to mention deleting or moving the ModelDB.db file before doing the sqlite3 load step. The errors are occurring because most rows are being inserted twice (or at least trying to). If you repeat those steps after moving the old database all should be good.
