### ISSUE TITLE
mdlcreatemodel error

### ISSUE THREAD

**Issue by jamesclulow** [ModelSEED/Model-SEED-core#74]
I am still having issues importing the models I created on ModelSEED for S. wittichii RW1 despite the fact that the recent update has solved login/account import issues. As such I just decided to try and run mdlcreatemodel and I get the following error.

tsf-wpa-1-3215:bin jamesclulow$ ./mdlcreatemodel -reconstruction 1 -genome 392499.4 -autocompletion 1 -overwrite 1
Directory:/Users/jamesclulow/Desktop/Model-SEED-core/data/models/jamesclulow/Seed392499.4.46352/0/
AND{SUBSYSTEM:One-carbon_metabolism_by_tetrahydropterines|SUBSYSTEM:Folate_Biosynthesis|!SUBSYSTEM:One-c
.
.
.
OR{SUBSYSTEM:Glutathione:_Biosynthesis_and_gamma-glutamyl_cycle`A`B|SUBSYSTEM:Glutathione:_Non-
AND{!NAME:Mycoplasma|!NAME:Spiroplasma|!NAME:Ureaplasma|!NAME:phytoplasma} : YES
AND{!NAME:Mycoplasma|!NAME:Spiroplasma|!NAME:Ureaplasma|!NAME:phytoplasma} : YES
OR{COMPOUND:cpd15665|COMPOUND:cpd15667|COMPOUND:cpd15668|COMPOUND:cpd15669} : YES
AND{COMPOUND:cpd00166} : NO
AND{COMPOUND:cpd00166} : NO
Total mass = -1.02, Reactant mass = -23.5435778113979, Product mass = 22.5235778113979
NOMATCH!
Whoops! We encountered an unrecoverable error.

A complete log of the problem has been printed to:

/Users/jamesclulow/Desktop/Model-SEED-core/.errors/error-vjLLv

The error log reads as follows:

> ModelDriver encountered an unrecoverable error:

```
Unsupported object class 'QUEUE' in database '/Users/jamesclulow/Desktop/Model-SEED-core/data/ModelDB/ModelDB.db'. at /Users/jamesclulow/Desktop/Model-SEED-core/lib/PPO/DBMaster.pm line 450.
```

> Model-SEED-core revision: a3c51c43c7a23fd5a58c2bcfb9adba1c1b860dbc

**Comment by cshenry** [comment]
This should be fixed now, but you'll need to run "ms-config load" following the update.
