### ISSUE TITLE
Model loading

### ISSUE THREAD

**Issue by alikpel** [ModelSEED/Model-SEED-core#75]
After successful model loading 

./fba-fva -model iJR904 
doesn't work

 Error log :

> ModelDriver encountered an unrecoverable error:

```
""ModelSEED::FIGMODEL"" at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 139
    ModelSEED::FIGMODEL::FIGMODELERROR('ModelSEED::FIGMODEL', 'Model iJR904 not found in database!') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pm line 5644
    ModelSEED::ModelDriver::fbafva('ModelSEED::ModelDriver=HASH(0x3c1a1a8)', 'fbafva', 'HASH(0x3bf5c08)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 87
    main::__ANON__() called at /usr/share/perl5/Try/Tiny.pm line 76
    eval {...} called at /usr/share/perl5/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x3c09dc0)', 'Try::Tiny::Catch=REF(0x3c0e158)') called at /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 91
    require /specific/disk1/home/alexnade/Model-SEED-core/lib/ModelSEED/ModelDriver.pl called at /specific/disk1/home/alexnade/Model-SEED-core/config//ModelSEEDbootstrap.pm line 20
    main::run() called at -e line 3 
```

> Model-SEED-core revision: a3c51c43c7a23fd5a58c2bcfb9adba1c1b860dbc

My Configuration file:

[Database]
# type is either sqlite or mysql

type=sqlite
# required for sqlite

filename=/specific/disk1/home/alexnade/Model-SEED-core/data/ModelDB/ModelDB.db
# required for mysql
# username=seed
# password=seedxhs
# host=localhost
# socket=/var/run/mysqld/mysqld.sock
# port=3306

[Optional]
dataDirectory=/specific/disk1/home/alexnade/Model-SEED-core/data/
# admin_users=admin1,admin2

[Optimizers]
includeDirectoryGLPK=/usr/lib/
libraryDirectoryGLPK=/usr/include/
# includeDirectoryCPLEX=/usr/local/lib/cplex121/include/
# libraryDirectoryCPLEX=/usr/local/lib/cplex121/lib/x86-64_sles9.0_3.3/static_pic/
# licenceDirectoryCPLEX=/usr/ilog/ilm/

Tnx,
Alik

**Comment by jamesclulow** [comment]
Look in data/models/**yourusername** The model that you imported will have a tag behind it specific to your workspace. i.e. iJR904 is called iJR904.46352 in my case. You need to add that tag on when trying the fba commands.

**Comment by jamesclulow** [comment]
The error is coming from the fact that it cannot find the model that you imported under the name iJR904. 
'Model iJR904 not found in database!'

**Comment by alikpel** [comment]
Great!  added the suffix and it worked.
tnx
