### ISSUE TITLE
mdlparsesbml error

### ISSUE THREAD

**Issue by jamesclulow** [ModelSEED/Model-SEED-core#78]
Two things to note here....
1.  Latest update has reintroduced two of the three errors that I found previously. One in FIGMODEL.pm and ModelDriver.pm where it is written parseSBMLtoTable instead of parseSBMLToTable. Search and you can find the two errors.
1. The other is that I seem to have issues with the output from the mdlparsesbml function. I tried to parse an SBML file downloaded from the web version of the Model SEED and it seems to have issues around the pegs.
   I noticed this when trying to do a subsequent mdlloadmodel and got the following error.

./Model-SEED-Core/bin/mdlloadmodel -name SwiSEEDv1 -genome 392499.4 -filename Model-SEED-Core/workspace/jamesclulow/default/SwiSeedv1-reactions.tbl -biomassFile Model-SEED-Core/workspace/jamesclulow/default/SwiSEEDv1-biomass.txt -overwrite 1

ModelDriver encountered an unrecoverable error:

```
Can't use an undefined value as an ARRAY reference at /Users/jamesclulow/Desktop/Model-SEED-core/lib/ModelSEED/FIGMODEL.pm line 2698.
```

Line 2698 reads as follows:
pegs => join("|",@{$row->{"ASSOCIATED PEG"}}),

I dug into the .tbl file and peg field is empty with the information to be found in other columns that are messy... essentially the parseSBML is doing something strange there and not creating a properly formated .tbl output. I can send the output file if needed?

**Comment by samseaver** [comment]
I designed parseSBMLToTable to output model files that can be recognized by the mdl-importmodel function, the PEGS column in the reactions.tbl file are recognized in mdl-importmodel.

Essentially mdl-loadmodel and mdl-importmodel should be able to recognize the same reactions.tbl file, so I'll look at mdl-loadmodel now.

As for the issues with losing changes in git, this has happened once to me once in a while, and I've yet to find out why it happens.

**Comment by samseaver** [comment]
OK, I've figured it out:

you cannot use the reactions.tbl file for mdl-loadmodel, you must first run mdl-printmodel to get the corresponding *.mdl file.
