### ISSUE TITLE
Error message while running non imported (not owned by user) models ./fbacheckgrowth

### ISSUE THREAD

**Issue by jplfaria** [ModelSEED/Model-SEED-core#79]
[jplfaria@biologin-4 bin]$ ./fbacheckgrowth -model iJR904  
Creating the model file: /vol/model-dev/MODEL_DEV_DB/ReactionDB/MFAToolkitOutputFiles/2400322/iJR904.tbl
Creating biochemistry provenance files
mkdir: cannot create directory `/vol/model-dev/MODEL_DEV_DB/ReactionDB/MFAToolkitOutputFiles/2400322/MFAOutput': File exists
User jplfaria does not have rights to set attribute growth with value 100.293 on object of type model at /home/jplfaria/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELdata.pm line 51
    ModelSEED::FIGMODEL::FIGMODELdata::AUTOLOAD('ModelSEED::FIGMODEL::FIGMODELdata=HASH(0xa73fc88)', 100.293) called at /home/jplfaria/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELmodel.pm line 7577
    ModelSEED::FIGMODEL::FIGMODELmodel::fbaCalculateGrowth('ModelSEED::FIGMODEL::FIGMODELmodel=HASH(0xa6d5fc8)', 'HASH(0xa73b260)') called at /home/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pm line 5560
    ModelSEED::ModelDriver::fbacheckgrowth('ModelSEED::ModelDriver=HASH(0xa564cf0)', 'fbacheckgrowth', 'HASH(0xa54d060)') called at /home/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 87
    main::**ANON**() called at /vol/model-prod/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Try/Tiny.pm line 76
    eval {...} called at /vol/model-prod/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0xa5465a0)', 'Try::Tiny::Catch=REF(0x8422628)') called at /home/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 91
    require /home/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pl called at /home/jplfaria/Model-SEED-core/config//ModelSEEDbootstrap.pm line 23
    main::run() called at -e line 3
User jplfaria does not have rights to set attribute noGrowthCompounds with value  on object of type model at /home/jplfaria/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELdata.pm line 51
    ModelSEED::FIGMODEL::FIGMODELdata::AUTOLOAD('ModelSEED::FIGMODEL::FIGMODELdata=HASH(0xa73fc88)', '') called at /home/jplfaria/Model-SEED-core/lib/ModelSEED/FIGMODEL/FIGMODELmodel.pm line 7578
    ModelSEED::FIGMODEL::FIGMODELmodel::fbaCalculateGrowth('ModelSEED::FIGMODEL::FIGMODELmodel=HASH(0xa6d5fc8)', 'HASH(0xa73b260)') called at /home/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pm line 5560
    ModelSEED::ModelDriver::fbacheckgrowth('ModelSEED::ModelDriver=HASH(0xa564cf0)', 'fbacheckgrowth', 'HASH(0xa54d060)') called at /home/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 87
    main::**ANON**() called at /vol/model-prod/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Try/Tiny.pm line 76
    eval {...} called at /vol/model-prod/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0xa5465a0)', 'Try::Tiny::Catch=REF(0x8422628)') called at /home/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pl line 91
    require /home/jplfaria/Model-SEED-core/lib/ModelSEED/ModelDriver.pl called at /home/jplfaria/Model-SEED-core/config//ModelSEEDbootstrap.pm line 23
    main::run() called at -e line 3
iJR904 grew in Complete media with rate:100.293 gm biomass/gm CDW hr.

**Comment by devoid** [comment]
I think these file exists errors were fixed (just warnings now.)
