### ISSUE TITLE
wrong KEGG aliases for Cytidine

### ISSUE THREAD

**Issue by mdejongh** [ModelSEED/Model-SEED-core#84]
The database has four KEGG ids for Cytidine (cpd00367), but only one is correct (C00475)

**Comment by pfrybar** [comment]
I've noticed a few other inaccuracies as well with some compounds/reactions. I think there are even some obsolete maps that are still being used. I don't believe we have synced/updated with KEGG in a while.

**Comment by samseaver** [comment]
We have discussed the need for a function that will allow compounds to be merged or split, such a function will need to extend into the database to make sure all the reactions are updated accordingly.

**Comment by samseaver** [comment]
I should point out here that the names used to match the compounds for each of the erroneous KEGG IDs are assigned to the correct compounds, so if one were to import a model, and the names were entered correctly, this is given precedence over the KEGG IDs themselves, so there will only be a problem if only KEGG IDs were used in generating the model.

**Comment by mdejongh** [comment]
The other concern is the Model SEED viewer - and other viewers like
CytoSEED - that display these incorrect associations.

On Fri, Nov 4, 2011 at 10:51 AM, samseaver
reply@reply.github.com
wrote:

> I should point out here that the names used to match the compounds for each of the erroneous KEGG IDs are assigned to the correct compounds, so if one were to import a model, and the names were entered correctly, this is given precedence over the KEGG IDs themselves, so there will only be a problem if only KEGG IDs were used in generating the model.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ModelSEED/Model-SEED-core/issues/84#issuecomment-2631738

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by samseaver** [comment]
So, I had a look at this, what needs to happen in the production database is that these lines need to be removed from the compound_alias table:

cpd00367      C00491  KEGG
cpd00367      C00542  KEGG
cpd00367      C02291  KEGG

and should be replaced with these lines:

cpd00381      C00491  KEGG
cpd00424      C00542  KEGG
cpd00424      C02291  KEGG

I did a systematic name search, to see if there were any other errors like this, and fortunately, there are none.

**Comment by samseaver** [comment]
I went ahead and did these updates in the production database, so the changes now appear correctly in the seed-viewer.

@mdejongh Do these changes appear in the cytoviewer?

@sdevoid Can these changes be propagated to the database dumps used for ModelSEEDCore?

**Comment by mdejongh** [comment]
Looks good in CytoSEED.

On Tue, Nov 8, 2011 at 12:43 PM, samseaver
reply@reply.github.com
wrote:

> I went ahead and did these updates in the production database, so the changes now appear correctly in the seed-viewer.
> 
> @mdejongh Do these changes appear in the cytoviewer?
> 
> @sdevoid Can these changes be propagated to the database dumps used for ModelSEEDCore?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ModelSEED/Model-SEED-core/issues/84#issuecomment-2670801

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429
