### ISSUE TITLE
Biomass not added to reaction_model table

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#85]
When using the biomassFile option in mdl-loadmodel, or just mdl-loadbiomass itself, it says that the biomass was successfully added.

However, its not added to the reaction_model table, this means that if one were to run an FBA job such as fba-checkgrowth, the model file that gets printed in the MFAOutputFiles directory does not contain the biomass function, and the job therefore does not run properly.

**Comment by jamesclulow** [comment]
Just noticed and was about to post the same issue...

**Comment by samseaver** [comment]
I've narrowed the problem down to this in FIGMODELmodel:

```
sub biomassReaction {
        my ($self,$newBiomass) = @_;  

        if (!defined($newBiomass) || $newBiomass eq $self->ppo()->biomassReaction()) {
                return $self->ppo()->biomassReaction();
        }
```

Apparently, even though the biomass reaction is not in the database reaction_model table, it is in the ppo object, so there's some disconnect here between the ppo object and the database, which I cannot seem to resolve.

**Comment by cshenry** [comment]
I rewrote the biomass function to resolve this issue, but let me know if the problem persists.

**Comment by cshenry** [comment]
I also tweaked the behavior of mdl-loadbiomass a bit. You might commonly do the following:
mdl-printbiomass bio00001?
cp bio00001.bof bio00002.bof
....change equation in file, but forget to change the "DATABASE" field...
mdl-loadbiomass bio00002?iJR904?
mdl-printmodel iJR904?

Then you might be really confused when your biomass was not changes to bio00002. I adjusted the system to use the ID from the filename if the file matches the regex bio\d+.

**Comment by samseaver** [comment]
I just wanted to add that in my latest update, I allow for a biomass to be loaded into a particular model even if that biomass did not exist.  The problem was that the function expects to overwrite the biomass and doesn't load it in the model if the overwrite option is not used.

Now, you can use the biomass and model options to load the biomass into a particular model without having to use the overwrite option.
