### ISSUE TITLE
Merging of compounds

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#87]
Due to the addition of names in the new KEGG update, there are more compounds that could be merged, and correctly so, such as:

http://seed-viewer.theseed.org/seedviewer.cgi?page=CompoundViewer&compound=cpd00970

and

http://seed-viewer.theseed.org/seedviewer.cgi?page=CompoundViewer&compound=cpd12232

What we need is a function, for those with "authority" to merge these two compounds into  a single identifier, but will also update all the reactions, and their equations, that contain both of these compounds.

**Comment by mdejongh** [comment]
I agree with you Sam, but note that these two compounds should not be
used in any of our models because they contain an unspecified
Nucleotide (represented as R).  I think Chris has a mechanism for
flagging certain reactions as non-usable for this reason.

Matt

On Mon, Nov 7, 2011 at 4:08 PM, samseaver
reply@reply.github.com
wrote:

> Due to the addition of names in the new KEGG update, there are more compounds that could be merged, and correctly so, such as:
> 
> http://seed-viewer.theseed.org/seedviewer.cgi?page=CompoundViewer&compound=cpd00970
> 
> and
> 
> http://seed-viewer.theseed.org/seedviewer.cgi?page=CompoundViewer&compound=cpd12232
> 
> What we need is a function, for those with "authority" to merge these two compounds into  a single identifier, but will also update all the reactions, and their equations, that contain both of these compounds.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ModelSEED/Model-SEED-core/issues/87

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by samseaver** [comment]
I've written a script that handles this.  I don't think I'm going to release it yet, especially not for use with the production database, but I update these tables:

COMPOUND
COMPOUND_ALIAS
COMPOUND_BIOMASS
COMPOUND_GROUPING
COMPOUND_REACTION
MEDIA_COMPOUND

and I also update the equations in REACTION and BIOMASS if they contain the compound that's to be merged.  On top of that, if the newly updated equation already exists in the tables, then I delete the old row as its now a duplicate.

Have I missed anything?

**Comment by samseaver** [comment]
I'm going to re-open a new issue that covers both compound merging and splitting.  I believe it should be implemented in the new biochemistry database.
