### ISSUE TITLE
Use of biomassFile option in loadmodel does not add biomass to model

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#89]
if I use ./mdl-loadmodel with the -biomassFile specifying the biomass (and the biomass reaction is not in the model itself) then the model doesn't add the biomass function to its list of reactions in reaction_model table.

**Comment by mdejongh** [comment]
I noticed this too.  Is it necessary to have the biomass reaction in
the reaction_model table?

Matt

On Tue, Nov 8, 2011 at 2:55 PM, samseaver
reply@reply.github.com
wrote:

> if I use ./mdl-loadmodel with the -biomassFile specifying the biomass (and the biomass reaction is not in the model itself) then the model doesn't add the biomass function to its list of reactions in reaction_model table.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ModelSEED/Model-SEED-core/issues/89

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by samseaver** [comment]
When you print the model, using mdl-printmodel, or via any FBA job (the FBA code prints the model into the FBA job directory) then it prints the model directly from the reaction_model table.  

Alternatively, since the model table has a biomassReaction field, I can see how a model can be printed without a biomass reaction in reaction_model, but the code would have to be updated to do this instead, everywhere a model is printed.  It's more straightforward just to make sure the biomass reaction is in the reaction_model table, unless I'm wrong.

**Comment by mdejongh** [comment]
It makes more sense to me NOT to put the biomass reaction in the
reaction_model table, since it can be looked up from the
biomassReaction field.  That way we don't have to remember to update
two different places that store the same information.  Any we won't
have to fix all the places in the code that match ids from
reaction_model using /rxn\d+/ as the pattern.  The biomass reaction is
different from other reactions, so it makes sense to store it and
treat it differently.

Matt

On Tue, Nov 8, 2011 at 4:15 PM, samseaver
reply@reply.github.com
wrote:

> When you print the model, using mdl-printmodel, or via any FBA job (the FBA code prints the model into the FBA job directory) then it prints the model directly from the reaction_model table.
> 
> Alternatively, since the model table has a biomassReaction field, I can see how a model can be printed without a biomass reaction in reaction_model, but the code would have to be updated to do this instead, everywhere a model is printed.  It's more straightforward just to make sure the biomass reaction is in the reaction_model table, unless I'm wrong.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ModelSEED/Model-SEED-core/issues/89#issuecomment-2673691

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by mdejongh** [comment]
Another reason not to put the biomass reaction in the "reaction_model" table is that biomass reactions aren't in the "reaction" table.

**Comment by samseaver** [comment]
I'm closing this issue because it has been fixed, the biomass reaction is now effectively being used by the FBA commands.  Matt's comments remain valid for the time being, but a new database schema is coming out that may render them invalid. :-)
