### ISSUE TITLE
compiled object files not included in .gitignore

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#9]
Because compilation of the mfatoolkit/Source results in object files that aren't included in the git repository, performing a status will highlight them.  I'd add them to .gitignore, but I'm not sure if that's entirely appropriate.

**Comment by devoid** [comment]
Fixed now. git will also not track `bin/*` unless it's already tracked. You would need to do an `git add -f` now to add such a file.
