### ISSUE TITLE
Need to be able to specify autoCompleteMedia when importing a model

### ISSUE THREAD

**Issue by mdejongh** [ModelSEED/Model-SEED-core#91]
Some models are autocompleted on known minimal media (e.g., Mycoplasma genitalium G-37/Seed243273.1 on SP4).  Need to be able to specify this when importing the model.  There are other data about models that are stored in the "model" table that should be dumpable/importable too (e.g., source, cell-wall-type).

**Comment by mdejongh** [comment]
I've added the capability of specifying autoCompleteMedia when using bin/mdl-loadmodel, but it will only work when the model is created brand new.  It seems like FIGMODEL's import_model_file should delete the modelObj when -overwrite is 1, so that attributes like genome and autoCompleteMedia get set correctly.

**Comment by mdejongh** [comment]
We should probably delete results from model_fva too.

**Comment by samseaver** [comment]
Has this been corrected?

**Comment by mdejongh** [comment]
I modified reloading a model to enable specifying the genome and autoCompleteMedia
