### ISSUE TITLE
[Feature request] Output of the modelimport

### ISSUE THREAD

**Issue by jplfaria** [ModelSEED/Model-SEED-core#92]
It would be good to see wich new compounds and reactions were added to the database, this information is currently printed to the screen, but there is no output fie.

**Comment by samseaver** [comment]
I fixed this so that all of the output that is normally printed to STDOUT by the mdl-importmodel script will instead go into a log file in the workspace, for ease of use.  The script will now print out the full name and path of this output file.

**Comment by jplfaria** [comment]
Hi Sam,

Looks like you forgot to check in this fix.

**Comment by samseaver** [comment]
I committed the change but forgot to 'push' it, it should be working now
