### ISSUE TITLE
mdlimportmodel Documentation

### ISSUE THREAD

**Issue by jamesclulow** [ModelSEED/Model-SEED-core#93]
It would be great to have an example file format of the tbl files for both reactions and compounds for the mdlimportmodel command. This would be useful as there is always some discrepancies between SBML files as to how compartments are flagged etc... An simple example would make it more clear as to what the file format needs to look like to be compatible.
Thanks.
James

**Comment by samseaver** [comment]
I extended the help page to show two very short examples, but these cannot be cut-and-pasted into a local file, and neither can I upload example files into the wiki.  I'll leave this open for now.

**Comment by devoid** [comment]
Closing. Help page is up to date; also part of the old interface.
