### ISSUE TITLE
Need a script to create a new reaction

### ISSUE THREAD

**Issue by mdejongh** [ModelSEED/Model-SEED-core#94]
I need to create some reactions, e.g., a Spermine ABC-transporter.  How do I do it?

**Comment by mdejongh** [comment]
The easiest way for me to do this would be to copy then edit an existing reaction object.  There is a subroutine in FIGMODELreaction.pm named copyReaction, but it is stubbed out for anything but biomass reactions.  Why?

**Comment by mdejongh** [comment]
Probably a better way to do this is to dump an existing reaction I want to copy/modify to file, then edit it, then load it.

**Comment by cshenry** [comment]
Yeah. I'll implement a print and load, the same way we did for media.

**Comment by samseaver** [comment]
From what I understand, this has been successfully implemented, so I'll close this issue for now.
