### ISSUE TITLE
Unable to create account/login

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#96]
With a fresh checkout of the ModelSEEDCore, I find that I am unable to use the ms-createuser, ms-login, ms-logout accounts, it keeps telling me there is a non-existent account and I'm being automatically logged out.

By "fresh", I mean I deleted everything and am switching from MySQL to SQLite, so my SQLite database is not responding.

**Comment by samseaver** [comment]
To add to this, I can't use ms-logout, and I create the appropriate line in the USERS column of the SQLite database manually, and each of the scripts that handle the user accounts insist that I am trying to use a non-existent account, so I am effectively stuck.

**Comment by samseaver** [comment]
I figured this out.  Since the default workspace is "public", the code will always look for a public account before doing anything else, and since the initial USERS table is empty, it fails to add me as a user.  I could get around this by manually adding a "public" account, with the password "public", but this needs to be either added to the USERS table, or to the config script.

**Comment by samseaver** [comment]
Finally, I should add that this issue is never thrown if a 'git pull' is run whilst logged in as a different user, which I believe is why it hasn't come up until now.

**Comment by devoid** [comment]
Closing.
