### ISSUE TITLE
Database defaults

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#97]
Currently, there are some fields that are not set to the pre-supposed defaults.  For example, there are NULL charges in the compound table.  The default value for these should be "10000000" as set by the import_model code. These NULL charges throw errors when an attempt is made to compare the charge of a compound.

As far as I can understand, the schema for the creation of a database table should set these defaults, and should also state whether a field should be "NON-NULL" by default.

What I'm proposing here is a more refined fined-tuned schema and an update of the data so that it is compatible.

**Comment by devoid** [comment]
Closing; MS objects can have defaults defined. If there is a specific object where a default `undef` value is invalid, create a new issue.
