### ISSUE TITLE
Use of dataDirectory in config file

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#99]
I tried using a local data directory in the config files, to keep my imported models in a more central location.  This works.

However, when running ms-config load, it does not copy ModelDB and ReactionDB into this new data directory, so when a command tries to call files within these directories, I get an error.  I don't get an error for access to the ModelDB database itself because of the previously set 'filename' option for the sqlite file.

**Comment by devoid** [comment]
Closed as won't fix. Old interface. Old Configuration system.
